<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Errors;

class BackendSrcAddressValidationResponsesValidationErrorResponseThrowable extends \RuntimeException
{
    public BackendSrcAddressValidationResponsesValidationErrorResponse $container;

    public function __construct(string $message, int $statusCode, BackendSrcAddressValidationResponsesValidationErrorResponse $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}