workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    kintsugi-overlay:
        inputs:
            - location: https://api-doc.trykintsugi.com/openapi.json
        overlays:
            - location: ./overlay.yaml
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: output.yaml
        registry:
            location: registry.speakeasyapi.dev/kintsugi-ai/tax-platform/kintsugi-overlay
targets:
    php:
        target: php
        source: kintsugi-overlay
        publish:
            packagist:
                username: $PACKAGIST_USERNAME
                token: $PACKAGIST_TOKEN
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/kintsugi-ai/tax-platform/kintsugi-overlay-php-code-samples
            labelOverride:
                fixedValue: PHP (SDK)
            blocking: false
