<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Models\Components;
use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class CreateTransactionByCustomerIdV1CustomersCustomerIdTransactionsPostRequest
{
    /**
     *
     * @var string $customerId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=customer_id')]
    public string $customerId;

    /**
     *
     * @var Components\TransactionCreate $transactionCreate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\TransactionCreate $transactionCreate;

    /**
     * @param  string  $customerId
     * @param  Components\TransactionCreate  $transactionCreate
     * @phpstan-pure
     */
    public function __construct(string $customerId, Components\TransactionCreate $transactionCreate)
    {
        $this->customerId = $customerId;
        $this->transactionCreate = $transactionCreate;
    }
}