<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Models\Components;
use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class CreateCustomerV1CustomersPostRequest
{
    /**
     *
     * @var Components\CustomerCreate $customerCreate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomerCreate $customerCreate;

    /**
     * The unique identifier for the organization making the request
     *
     * @var ?string $xOrganizationId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-organization-id')]
    public ?string $xOrganizationId;

    /**
     * @param  Components\CustomerCreate  $customerCreate
     * @param  ?string  $xOrganizationId
     * @phpstan-pure
     */
    public function __construct(Components\CustomerCreate $customerCreate, ?string $xOrganizationId = null)
    {
        $this->customerCreate = $customerCreate;
        $this->xOrganizationId = $xOrganizationId;
    }
}