<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class DeletePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdDeleteRequest
{
    /**
     * The unique identifier of the physical
     *
     *                                 nexus to delete.
     *
     * @var string $physicalNexusId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=physical_nexus_id')]
    public string $physicalNexusId;

    /**
     * @param  string  $physicalNexusId
     * @phpstan-pure
     */
    public function __construct(string $physicalNexusId)
    {
        $this->physicalNexusId = $physicalNexusId;
    }
}