<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Models\Components;
use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class DeregisterRegistrationV1RegistrationsRegistrationIdDeregisterPostRequest
{
    /**
     * The unique identifier of the registration to deregister.
     *
     * @var string $registrationId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=registration_id')]
    public string $registrationId;

    /**
     *
     * @var \KintsugiTax\SDK\Models\Components\DeregisterRegistrationRequest $deregisterRegistrationRequest
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\DeregisterRegistrationRequest $deregisterRegistrationRequest;

    /**
     * The unique identifier for the organization making the request
     *
     * @var ?string $xOrganizationId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-organization-id')]
    public ?string $xOrganizationId;

    /**
     * @param  string  $registrationId
     * @param  \KintsugiTax\SDK\Models\Components\DeregisterRegistrationRequest  $deregisterRegistrationRequest
     * @param  ?string  $xOrganizationId
     * @phpstan-pure
     */
    public function __construct(string $registrationId, Components\DeregisterRegistrationRequest $deregisterRegistrationRequest, ?string $xOrganizationId = null)
    {
        $this->registrationId = $registrationId;
        $this->deregisterRegistrationRequest = $deregisterRegistrationRequest;
        $this->xOrganizationId = $xOrganizationId;
    }
}