<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class GetAttachmentsForExemptionV1ExemptionsExemptionIdAttachmentsGetRequest
{
    /**
     * The unique identifier for the exemption
     *
     *         whose attachments are being retrieved.
     *
     * @var string $exemptionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=exemption_id')]
    public string $exemptionId;

    /**
     * @param  string  $exemptionId
     * @phpstan-pure
     */
    public function __construct(string $exemptionId)
    {
        $this->exemptionId = $exemptionId;
    }
}