<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Models\Components;
use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class GetCustomersV1Request
{
    /**
     * Search term to filter customers by name or other details
     *
     * @var ?string $searchQuery
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=search_query')]
    public ?string $searchQuery = null;

    /**
     * Country code in ISO 3166-1 alpha-2 format (e.g., 'US')
     *
     * @var ?array<Components\CountryCodeEnum> $country
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=country')]
    public ?array $country = null;

    /**
     * State or province code to filter customers
     *
     * @var ?string $state
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=state')]
    public ?string $state = null;

    /**
     * Filter customers by source (comma-separated)
     *
     * @var ?string $sourceIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=source__in')]
    public ?string $sourceIn = null;

    /**
     * Comma-separated list of fields to sort results by.
     *
     * @var ?string $orderBy
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=order_by')]
    public ?string $orderBy = null;

    /**
     * Page number
     *
     * @var ?int $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;

    /**
     * Page size
     *
     * @var ?int $size
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=size')]
    public ?int $size = null;

    /**
     * @param  ?string  $searchQuery
     * @param  ?array<Components\CountryCodeEnum>  $country
     * @param  ?string  $state
     * @param  ?string  $sourceIn
     * @param  ?string  $orderBy
     * @param  ?int  $page
     * @param  ?int  $size
     * @phpstan-pure
     */
    public function __construct(?string $searchQuery = null, ?array $country = null, ?string $state = null, ?string $sourceIn = null, ?string $orderBy = null, ?int $page = 1, ?int $size = 50)
    {
        $this->searchQuery = $searchQuery;
        $this->country = $country;
        $this->state = $state;
        $this->sourceIn = $sourceIn;
        $this->orderBy = $orderBy;
        $this->page = $page;
        $this->size = $size;
    }
}