<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;

use OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class GetExemptionByIdV1ExemptionsExemptionIdGetSecurity
{
    /**
     *
     * @var ?string $apiKeyHeader
     */
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=X-API-KEY')]
    public ?string $apiKeyHeader = null;

    /**
     *
     * @var ?string $httpBearer
     */
    #[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
    public ?string $httpBearer = null;

    /**
     * @param  ?string  $apiKeyHeader
     * @param  ?string  $httpBearer
     * @phpstan-pure
     */
    public function __construct(?string $apiKeyHeader = null, ?string $httpBearer = null)
    {
        $this->apiKeyHeader = $apiKeyHeader;
        $this->httpBearer = $httpBearer;
    }
}