<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Models\Components;
use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class GetExemptionsV1ExemptionsGetRequest
{
    /**
     * Search term to filter exemptions by exemption ID, customer name, or customer email
     *
     * @var ?string $searchQuery
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=search_query')]
    public ?string $searchQuery = null;

    /**
     * Country code in ISO 3166-1 alpha-2 format
     *
     * @var ?array<Components\CountryCodeEnum> $countryCode
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=country_code')]
    public ?array $countryCode = null;

    /**
     * Jurisdiction identifier
     *
     * @var ?string $jurisdiction
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=jurisdiction')]
    public ?string $jurisdiction = null;

    /**
     * Start date for filtering exemptions
     *
     * @var ?string $startDate
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=start_date')]
    public ?string $startDate = null;

    /**
     * End date for filtering exemptions
     *
     * @var ?string $endDate
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=end_date')]
    public ?string $endDate = null;

    /**
     * Customer ID to filter exemptions
     *
     * @var ?string $customerId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=customer_id')]
    public ?string $customerId = null;

    /**
     * Transaction ID to filter exemptions
     *
     * @var ?string $transactionId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=transaction_id')]
    public ?string $transactionId = null;

    /**
     * Filter exemptions by their status
     *
     * @var ?string $statusIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status__in')]
    public ?string $statusIn = null;

    /**
     * Fields to sort by (comma-separated)
     *
     * @var ?string $orderBy
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=order_by')]
    public ?string $orderBy = null;

    /**
     * Page number
     *
     * @var ?int $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;

    /**
     * Page size
     *
     * @var ?int $size
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=size')]
    public ?int $size = null;

    /**
     * @param  ?string  $searchQuery
     * @param  ?string  $statusIn
     * @param  ?array<Components\CountryCodeEnum>  $countryCode
     * @param  ?string  $jurisdiction
     * @param  ?string  $startDate
     * @param  ?string  $endDate
     * @param  ?string  $customerId
     * @param  ?string  $transactionId
     * @param  ?string  $orderBy
     * @param  ?int  $page
     * @param  ?int  $size
     * @phpstan-pure
     */
    public function __construct(?string $searchQuery = null, ?array $countryCode = null, ?string $jurisdiction = null, ?string $startDate = null, ?string $endDate = null, ?string $customerId = null, ?string $transactionId = null, ?string $statusIn = 'ACTIVE,INACTIVE,EXPIRED', ?string $orderBy = 'end_date,FEIN,sales_tax_id,status', ?int $page = 1, ?int $size = 50)
    {
        $this->searchQuery = $searchQuery;
        $this->countryCode = $countryCode;
        $this->jurisdiction = $jurisdiction;
        $this->startDate = $startDate;
        $this->endDate = $endDate;
        $this->customerId = $customerId;
        $this->transactionId = $transactionId;
        $this->statusIn = $statusIn;
        $this->orderBy = $orderBy;
        $this->page = $page;
        $this->size = $size;
    }
}