<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class GetFilingByIdV1FilingsFilingIdGetRequest
{
    /**
     * Unique identifier for the filing to retrieve.
     *
     * @var string $filingId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=filing_id')]
    public string $filingId;

    /**
     * @param  string  $filingId
     * @phpstan-pure
     */
    public function __construct(string $filingId)
    {
        $this->filingId = $filingId;
    }
}