<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Models\Components;
use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class GetFilingsV1FilingsGetRequest
{
    /**
     * Filter filings with a start date greater than or equal to this date.
     *
     * @var ?string $startDate
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=start_date')]
    public ?string $startDate = null;

    /**
     * Filter filings with an end date less than or equal to this date.
     *
     * @var ?string $endDate
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=end_date')]
    public ?string $endDate = null;

    /**
     * Filter filings filed on or after this date.
     *
     * @var ?string $dateFiledGte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=date_filed__gte')]
    public ?string $dateFiledGte = null;

    /**
     * Filter filings filed on or before this date.
     *
     * @var ?string $dateFiledLte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=date_filed__lte')]
    public ?string $dateFiledLte = null;

    /**
     * Comma-separated list of fields to sort the results.
     *
     * @var ?string $orderBy
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=order_by')]
    public ?string $orderBy = null;

    /**
     * Filter filings by state code (e.g., CA for California).
     *
     * @var ?string $stateCode
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=state_code')]
    public ?string $stateCode = null;

    /**
     * Filter filings by country code in ISO 3166-1 alpha-2 format (e.g., US).
     *
     * @var ?array<Components\CountryCodeEnum> $countryCode
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=country_code')]
    public ?array $countryCode = null;

    /**
     * Filter filings by status
     *
     * @var ?string $statusIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status__in')]
    public ?string $statusIn = null;

    /**
     * Page number
     *
     * @var ?int $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;

    /**
     * Page size
     *
     * @var ?int $size
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=size')]
    public ?int $size = null;

    /**
     * @param  ?string  $statusIn
     * @param  ?string  $startDate
     * @param  ?string  $endDate
     * @param  ?string  $dateFiledGte
     * @param  ?string  $dateFiledLte
     * @param  ?string  $orderBy
     * @param  ?string  $stateCode
     * @param  ?array<Components\CountryCodeEnum>  $countryCode
     * @param  ?int  $page
     * @param  ?int  $size
     * @phpstan-pure
     */
    public function __construct(?string $startDate = null, ?string $endDate = null, ?string $dateFiledGte = null, ?string $dateFiledLte = null, ?string $orderBy = null, ?string $stateCode = null, ?array $countryCode = null, ?string $statusIn = 'FILED,FILING,UNFILED,PAUSED', ?int $page = 1, ?int $size = 50)
    {
        $this->startDate = $startDate;
        $this->endDate = $endDate;
        $this->dateFiledGte = $dateFiledGte;
        $this->dateFiledLte = $dateFiledLte;
        $this->orderBy = $orderBy;
        $this->stateCode = $stateCode;
        $this->countryCode = $countryCode;
        $this->statusIn = $statusIn;
        $this->page = $page;
        $this->size = $size;
    }
}