<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use Brick\DateTime\LocalDate;
use KintsugiTax\SDK\Models\Components;
use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class GetFilingsV1FilingsGetRequest
{
    /**
     * The unique identifier for the organization making the request
     *
     * @var ?string $xOrganizationId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-organization-id')]
    public ?string $xOrganizationId;

    /**
     * Filter filings by status
     *
     * @var ?string $statusIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status__in')]
    public ?string $statusIn = null;

    /**
     * Filter filings with a start date greater than or equal to this date.
     *
     * @var ?LocalDate $startDate
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=start_date,dateTimeFormat=Y-m-d')]
    public ?LocalDate $startDate = null;

    /**
     * Filter filings with an end date less than or equal to this date.
     *
     * @var ?LocalDate $endDate
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=end_date,dateTimeFormat=Y-m-d')]
    public ?LocalDate $endDate = null;

    /**
     * Filter filings filed on or after this date.
     *
     * @var ?LocalDate $dateFiledGte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=date_filed__gte,dateTimeFormat=Y-m-d')]
    public ?LocalDate $dateFiledGte = null;

    /**
     * Filter filings filed on or before this date.
     *
     * @var ?LocalDate $dateFiledLte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=date_filed__lte,dateTimeFormat=Y-m-d')]
    public ?LocalDate $dateFiledLte = null;

    /**
     * Comma-separated list of fields to sort the results.
     *
     * @var ?string $orderBy
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=order_by')]
    public ?string $orderBy = null;

    /**
     * Filter filings by state code (e.g., CA for California).
     *
     * @var ?string $stateCode
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=state_code')]
    public ?string $stateCode = null;

    /**
     * Filter filings by country code in ISO 3166-1 alpha-2 format (e.g., US).
     *
     * @var ?array<\KintsugiTax\SDK\Models\Components\CountryCodeEnum|string> $countryCode
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=country_code')]
    public ?array $countryCode = null;

    /**
     * Filter filings by category (e.g., REGULAR, BACK_FILING, AMENDMENT).
     *
     * @var ?string $filingCategoryIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=filing_category__in')]
    public ?string $filingCategoryIn = null;

    /**
     * Filter filings by tax type. Multiple tax types can be
     *
     *         passed, separated by commas (SALES_TAX, USE_TAX, SALES_AND_USE_TAX).
     *
     * @var ?string $taxTypeIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tax_type__in')]
    public ?string $taxTypeIn = null;

    /**
     * Page number
     *
     * @var ?int $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;

    /**
     * Page size
     *
     * @var ?int $size
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=size')]
    public ?int $size = null;

    /**
     * @param  ?int  $page
     * @param  ?int  $size
     * @param  ?string  $xOrganizationId
     * @param  ?string  $statusIn
     * @param  ?LocalDate  $startDate
     * @param  ?LocalDate  $endDate
     * @param  ?LocalDate  $dateFiledGte
     * @param  ?LocalDate  $dateFiledLte
     * @param  ?string  $orderBy
     * @param  ?string  $stateCode
     * @param  ?array<\KintsugiTax\SDK\Models\Components\CountryCodeEnum|string>  $countryCode
     * @param  ?string  $filingCategoryIn
     * @param  ?string  $taxTypeIn
     * @phpstan-pure
     */
    public function __construct(?string $xOrganizationId = null, ?string $statusIn = null, ?LocalDate $startDate = null, ?LocalDate $endDate = null, ?LocalDate $dateFiledGte = null, ?LocalDate $dateFiledLte = null, ?string $orderBy = null, ?string $stateCode = null, ?array $countryCode = null, ?string $filingCategoryIn = null, ?string $taxTypeIn = null, ?int $page = 1, ?int $size = 50)
    {
        $this->xOrganizationId = $xOrganizationId;
        $this->statusIn = $statusIn;
        $this->startDate = $startDate;
        $this->endDate = $endDate;
        $this->dateFiledGte = $dateFiledGte;
        $this->dateFiledLte = $dateFiledLte;
        $this->orderBy = $orderBy;
        $this->stateCode = $stateCode;
        $this->countryCode = $countryCode;
        $this->filingCategoryIn = $filingCategoryIn;
        $this->taxTypeIn = $taxTypeIn;
        $this->page = $page;
        $this->size = $size;
    }
}