<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Models\Components;
use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class GetPhysicalNexusCategoriesV1NexusPhysicalNexusCategoriesGetRequest
{
    /**
     * The unique identifier for the organization making the request
     *
     * @var ?string $xOrganizationId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-organization-id')]
    public ?string $xOrganizationId;

    /**
     *
     * @var ?\KintsugiTax\SDK\Models\Components\CountryCodeEnum $countryCode
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=country_code')]
    public ?Components\CountryCodeEnum $countryCode = null;

    /**
     *
     * @var ?string $stateCode
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=state_code')]
    public ?string $stateCode = null;

    /**
     * @param  ?string  $xOrganizationId
     * @param  ?\KintsugiTax\SDK\Models\Components\CountryCodeEnum  $countryCode
     * @param  ?string  $stateCode
     * @phpstan-pure
     */
    public function __construct(?string $xOrganizationId = null, ?Components\CountryCodeEnum $countryCode = null, ?string $stateCode = null)
    {
        $this->xOrganizationId = $xOrganizationId;
        $this->countryCode = $countryCode;
        $this->stateCode = $stateCode;
    }
}