<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class GetProductByIdV1ProductsProductIdGetRequest
{
    /**
     * The unique identifier for the product you want to retrieve.
     *
     * @var string $productId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=product_id')]
    public string $productId;

    /**
     * The unique identifier for the organization making the request
     *
     * @var ?string $xOrganizationId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-organization-id')]
    public ?string $xOrganizationId;

    /**
     * @param  string  $productId
     * @param  ?string  $xOrganizationId
     * @phpstan-pure
     */
    public function __construct(string $productId, ?string $xOrganizationId = null)
    {
        $this->productId = $productId;
        $this->xOrganizationId = $xOrganizationId;
    }
}