<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class GetPhysicalNexusV1NexusPhysicalNexusGetRequest
{
    /**
     * The unique identifier for the organization making the request
     *
     * @var ?string $xOrganizationId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-organization-id')]
    public ?string $xOrganizationId;

    /**
     *
     * @var ?string $countryCode
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=country_code')]
    public ?string $countryCode = null;

    /**
     *
     * @var ?string $stateCode
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=state_code')]
    public ?string $stateCode = null;

    /**
     *
     * @var ?string $orderBy
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=order_by')]
    public ?string $orderBy = null;

    /**
     * Page number
     *
     * @var ?int $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;

    /**
     * Page size
     *
     * @var ?int $size
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=size')]
    public ?int $size = null;

    /**
     * @param  ?int  $page
     * @param  ?int  $size
     * @param  ?string  $xOrganizationId
     * @param  ?string  $countryCode
     * @param  ?string  $stateCode
     * @param  ?string  $orderBy
     * @phpstan-pure
     */
    public function __construct(?string $xOrganizationId = null, ?string $countryCode = null, ?string $stateCode = null, ?string $orderBy = null, ?int $page = 1, ?int $size = 50)
    {
        $this->xOrganizationId = $xOrganizationId;
        $this->countryCode = $countryCode;
        $this->stateCode = $stateCode;
        $this->orderBy = $orderBy;
        $this->page = $page;
        $this->size = $size;
    }
}