<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class GetTransactionByExternalIdV1TransactionsExternalExternalIdGetRequest
{
    /**
     * The unique external identifier of the transaction.
     *
     * @var string $externalId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=external_id')]
    public string $externalId;

    /**
     * @param  string  $externalId
     * @phpstan-pure
     */
    public function __construct(string $externalId)
    {
        $this->externalId = $externalId;
    }
}