<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class ListRegistrationJurisdictionsV1RegistrationsJurisdictionsGetRequest
{
    /**
     * The unique identifier for the organization making the request
     *
     * @var ?string $xOrganizationId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-organization-id')]
    public ?string $xOrganizationId;

    /**
     * Filter by registration status (comma-separated); same as GET /registrations.
     *
     * @var ?string $statusIn
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status__in')]
    public ?string $statusIn = null;

    /**
     * @param  ?string  $statusIn
     * @param  ?string  $xOrganizationId
     * @phpstan-pure
     */
    public function __construct(?string $xOrganizationId = null, ?string $statusIn = 'REGISTERED,PROCESSING,UNREGISTERED,DEREGISTERING,DEREGISTERED,CANCELLED,VALIDATING,AWAITING_CLARIFICATION,SELF_MANAGED')
    {
        $this->xOrganizationId = $xOrganizationId;
        $this->statusIn = $statusIn;
    }
}