<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Models\Components;
use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class POSTCreateCreditNoteByTransactionIdRequest
{
    /**
     *
     * @var string $originalTransactionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=original_transaction_id')]
    public string $originalTransactionId;

    /**
     *
     * @var Components\CreditNoteCreate $creditNoteCreate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CreditNoteCreate $creditNoteCreate;

    /**
     * The unique identifier for the organization making the request
     *
     * @var ?string $xOrganizationId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-organization-id')]
    public ?string $xOrganizationId;

    /**
     * @param  string  $originalTransactionId
     * @param  Components\CreditNoteCreate  $creditNoteCreate
     * @param  ?string  $xOrganizationId
     * @phpstan-pure
     */
    public function __construct(string $originalTransactionId, Components\CreditNoteCreate $creditNoteCreate, ?string $xOrganizationId = null)
    {
        $this->originalTransactionId = $originalTransactionId;
        $this->creditNoteCreate = $creditNoteCreate;
        $this->xOrganizationId = $xOrganizationId;
    }
}