<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Operations;

use KintsugiTax\SDK\Models\Components;
use KintsugiTax\SDK\Utils\SpeakeasyMetadata;
class UpdateTransactionV1TransactionsTransactionIdPutRequest
{
    /**
     *
     * @var string $transactionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=transaction_id')]
    public string $transactionId;

    /**
     *
     * @var Components\TransactionUpdate $transactionUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\TransactionUpdate $transactionUpdate;

    /**
     * The unique identifier for the organization making the request
     *
     * @var ?string $xOrganizationId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-organization-id')]
    public ?string $xOrganizationId;

    /**
     * @param  string  $transactionId
     * @param  Components\TransactionUpdate  $transactionUpdate
     * @param  ?string  $xOrganizationId
     * @phpstan-pure
     */
    public function __construct(string $transactionId, Components\TransactionUpdate $transactionUpdate, ?string $xOrganizationId = null)
    {
        $this->transactionId = $transactionId;
        $this->transactionUpdate = $transactionUpdate;
        $this->xOrganizationId = $xOrganizationId;
    }
}