<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


enum AddressType: string
{
    case BillTo = 'BILL_TO';
    case ShipTo = 'SHIP_TO';
    case ShipFrom = 'SHIP_FROM';
    case BillFrom = 'BILL_FROM';
}
