<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** ArizonaFields - State-specific fields for Arizona TPT registration import. */
class ArizonaFields
{
    /**
     *
     * @var \KintsugiTax\SDK\Models\Components\ArizonaRegistrationType $registrationType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ArizonaRegistrationType')]
    public ArizonaRegistrationType $registrationType;

    /**
     * Business name as registered with the state of Arizona.
     *
     * @var string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_name')]
    public string $businessName;

    /**
     * Arizona state-issued sales tax number (AZ State Tax ID).
     *
     * @var string $salesTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sales_tax_id')]
    public string $salesTaxId;

    /**
     * Business location ID as shown in AZTaxes.gov.
     *
     * @var string $locationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('location_id')]
    public string $locationId;

    /**
     * Whether the customer has completed MFA setup in their Arizona AZTaxes.gov account.
     *
     * @var ?bool $mfaCompleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mfa_completed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $mfaCompleted = null;

    /**
     * @param  \KintsugiTax\SDK\Models\Components\ArizonaRegistrationType  $registrationType
     * @param  string  $businessName
     * @param  string  $salesTaxId
     * @param  string  $locationId
     * @param  ?bool  $mfaCompleted
     * @phpstan-pure
     */
    public function __construct(ArizonaRegistrationType $registrationType, string $businessName, string $salesTaxId, string $locationId, ?bool $mfaCompleted = false)
    {
        $this->registrationType = $registrationType;
        $this->businessName = $businessName;
        $this->salesTaxId = $salesTaxId;
        $this->locationId = $locationId;
        $this->mfaCompleted = $mfaCompleted;
    }
}