<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** Attachments - List of attachments associated with the filing, if any. */
class Attachments
{

    public function __construct()
    {
    }
}