<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


class BackendSrcAddressValidationResponsesValidationErrorItem
{
    /**
     * Type of validation error
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * Location of error
     *
     * @var array<string> $loc
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('loc')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $loc;

    /**
     * Error message
     *
     * @var string $msg
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('msg')]
    public string $msg;

    /**
     * Invalid input value
     *
     * @var mixed $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    public mixed $input;

    /**
     * Additional context
     *
     * @var array<string, mixed> $ctx
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ctx')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>')]
    public array $ctx;

    /**
     * @param  string  $type
     * @param  array<string>  $loc
     * @param  string  $msg
     * @param  mixed  $input
     * @param  array<string, mixed>  $ctx
     * @phpstan-pure
     */
    public function __construct(string $type, array $loc, string $msg, mixed $input, array $ctx)
    {
        $this->type = $type;
        $this->loc = $loc;
        $this->msg = $msg;
        $this->input = $input;
        $this->ctx = $ctx;
    }
}