<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;

use Brick\DateTime\LocalDate;
class BackendSrcExemptionsSerializersExemptionRead
{
    /**
     * Start date for the exemption validity period (YYYY-MM-DD format)
     *
     * @var LocalDate $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_date')]
    public LocalDate $startDate;

    /**
     * Unique identifier for the exemption
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var ExemptionType $exemptionType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exemption_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\ExemptionType')]
    public ExemptionType $exemptionType;

    /**
     *
     * @var ExemptionStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\ExemptionStatus')]
    public ExemptionStatus $status;

    /**
     * Country code in ISO 3166-1 alpha-2 format (e.g., 'US')
     *
     * @var ?CountryCodeEnum $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country_code')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\CountryCodeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CountryCodeEnum $countryCode = null;

    /**
     * The jurisdiction identifier for the exemption
     *
     * @var ?string $jurisdiction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('jurisdiction')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $jurisdiction = null;

    /**
     * End date for the exemption validity period (YYYY-MM-DD format)
     *
     * @var ?LocalDate $endDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $endDate = null;

    /**
     * Unique identifier for the transaction, if applicable
     *
     * @var ?string $transactionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transaction_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transactionId = null;

    /**
     * Federal Employer Identification Number
     *
     * @var ?string $fein
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('FEIN')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $fein = null;

    /**
     * Sales tax ID for the exemption
     *
     * @var ?string $salesTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sales_tax_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $salesTaxId = null;

    /**
     * Details of the customer associated with the exemption
     *
     * @var ?CustomerRead $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\CustomerRead|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CustomerRead $customer = null;

    /**
     * List of attachments related to the exemption
     *
     * @var ?array<AttachmentRead> $attachment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attachment')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\OpenAPI\OpenAPI\Models\Components\AttachmentRead>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $attachment = null;

    /**
     * Indicates whether the exemption is for a reseller
     *
     * @var ?bool $reseller
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reseller')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $reseller = null;

    /**
     * @param  LocalDate  $startDate
     * @param  string  $id
     * @param  ExemptionType  $exemptionType
     * @param  ExemptionStatus  $status
     * @param  ?bool  $reseller
     * @param  ?CountryCodeEnum  $countryCode
     * @param  ?string  $jurisdiction
     * @param  ?LocalDate  $endDate
     * @param  ?string  $transactionId
     * @param  ?string  $fein
     * @param  ?string  $salesTaxId
     * @param  ?CustomerRead  $customer
     * @param  ?array<AttachmentRead>  $attachment
     * @phpstan-pure
     */
    public function __construct(LocalDate $startDate, string $id, ExemptionType $exemptionType, ExemptionStatus $status, ?CountryCodeEnum $countryCode = null, ?string $jurisdiction = null, ?LocalDate $endDate = null, ?string $transactionId = null, ?string $fein = null, ?string $salesTaxId = null, ?CustomerRead $customer = null, ?array $attachment = null, ?bool $reseller = false)
    {
        $this->startDate = $startDate;
        $this->id = $id;
        $this->exemptionType = $exemptionType;
        $this->status = $status;
        $this->countryCode = $countryCode;
        $this->jurisdiction = $jurisdiction;
        $this->endDate = $endDate;
        $this->transactionId = $transactionId;
        $this->fein = $fein;
        $this->salesTaxId = $salesTaxId;
        $this->customer = $customer;
        $this->attachment = $attachment;
        $this->reseller = $reseller;
    }
}