<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;

use Brick\DateTime\LocalDate;
class BackendSrcExemptionsModelsExemptionRead
{
    /**
     *
     * @var ExemptionType $exemptionType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exemption_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ExemptionType')]
    public ExemptionType $exemptionType;

    /**
     * Start date for the exemption validity period (YYYY-MM-DD format)
     *
     * @var LocalDate $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_date')]
    public LocalDate $startDate;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The jurisdiction identifier for the exemption
     *
     * @var ?string $jurisdiction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('jurisdiction')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $jurisdiction = null;

    /**
     *
     * @var ?CountryCodeEnum $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country_code')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CountryCodeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CountryCodeEnum $countryCode = null;

    /**
     * End date for the exemption validity period (YYYY-MM-DD format)
     *
     * @var ?string $endDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $endDate = null;

    /**
     * Unique identifier for the customer associated with the exemption
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     * Unique identifier for the transaction
     *
     *         associated with the exemption, if applicable.
     *
     * @var ?string $transactionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transaction_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transactionId = null;

    /**
     * Federal Employer Identification Number
     *
     *         associated with the exemption.
     *
     * @var ?string $fein
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('FEIN')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $fein = null;

    /**
     * Sales tax ID for the exemption
     *
     * @var ?string $salesTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sales_tax_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $salesTaxId = null;

    /**
     *
     * @var ?ExemptionStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ExemptionStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ExemptionStatus $status = null;

    /**
     *
     * @var ?string $customerName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerName = null;

    /**
     *
     * @var ?string $attachmentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attachment_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $attachmentId = null;

    /**
     * Indicates whether the exemption is for a reseller
     *
     * @var ?bool $reseller
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reseller')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $reseller = null;

    /**
     * @param  ExemptionType  $exemptionType
     * @param  LocalDate  $startDate
     * @param  string  $id
     * @param  ?string  $jurisdiction
     * @param  ?CountryCodeEnum  $countryCode
     * @param  ?string  $endDate
     * @param  ?string  $customerId
     * @param  ?string  $transactionId
     * @param  ?bool  $reseller
     * @param  ?string  $fein
     * @param  ?string  $salesTaxId
     * @param  ?ExemptionStatus  $status
     * @param  ?string  $customerName
     * @param  ?string  $attachmentId
     * @phpstan-pure
     */
    public function __construct(ExemptionType $exemptionType, LocalDate $startDate, string $id, ?string $jurisdiction = null, ?CountryCodeEnum $countryCode = null, ?string $endDate = null, ?string $customerId = null, ?string $transactionId = null, ?string $fein = null, ?string $salesTaxId = null, ?ExemptionStatus $status = null, ?string $customerName = null, ?string $attachmentId = null, ?bool $reseller = false)
    {
        $this->exemptionType = $exemptionType;
        $this->startDate = $startDate;
        $this->id = $id;
        $this->jurisdiction = $jurisdiction;
        $this->countryCode = $countryCode;
        $this->endDate = $endDate;
        $this->customerId = $customerId;
        $this->transactionId = $transactionId;
        $this->fein = $fein;
        $this->salesTaxId = $salesTaxId;
        $this->status = $status;
        $this->customerName = $customerName;
        $this->attachmentId = $attachmentId;
        $this->reseller = $reseller;
    }
}