<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;

use Brick\DateTime\LocalDate;
class BackFilingRequestPeriod
{
    /**
     *
     * @var LocalDate $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_date')]
    public LocalDate $startDate;

    /**
     *
     * @var LocalDate $endDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_date')]
    public LocalDate $endDate;

    /**
     *
     * @var string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    public string $label;

    /**
     * @param  LocalDate  $startDate
     * @param  LocalDate  $endDate
     * @param  string  $label
     * @phpstan-pure
     */
    public function __construct(LocalDate $startDate, LocalDate $endDate, string $label)
    {
        $this->startDate = $startDate;
        $this->endDate = $endDate;
        $this->label = $label;
    }
}