<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** CaliforniaFields - State-specific fields for California CDTFA portal registration import. */
class CaliforniaFields
{
    /**
     *
     * @var \KintsugiTax\SDK\Models\Components\CaliforniaRegistrationType $registrationType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CaliforniaRegistrationType')]
    public CaliforniaRegistrationType $registrationType;

    /**
     * Business name as registered with CDTFA.
     *
     * @var string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_name')]
    public string $businessName;

    /**
     * California Sales and Use Tax ID (seller's permit / CDTFA account number).
     *
     * @var string $salesTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sales_tax_id')]
    public string $salesTaxId;

    /**
     * Optional at import; customers add this in registration credentials after CDTFA issues it. Third-party access security code from CDTFA Online Services so Kintsugi can file on your behalf.
     *
     * @var ?string $cdtfaThirdPartyAccessSecurityCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cdtfa_third_party_access_security_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $cdtfaThirdPartyAccessSecurityCode = null;

    /**
     * Whether the customer has completed MFA setup in their California CDTFA account.
     *
     * @var ?bool $mfaCompleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mfa_completed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $mfaCompleted = null;

    /**
     * @param  \KintsugiTax\SDK\Models\Components\CaliforniaRegistrationType  $registrationType
     * @param  string  $businessName
     * @param  string  $salesTaxId
     * @param  ?bool  $mfaCompleted
     * @param  ?string  $cdtfaThirdPartyAccessSecurityCode
     * @phpstan-pure
     */
    public function __construct(CaliforniaRegistrationType $registrationType, string $businessName, string $salesTaxId, ?string $cdtfaThirdPartyAccessSecurityCode = null, ?bool $mfaCompleted = false)
    {
        $this->registrationType = $registrationType;
        $this->businessName = $businessName;
        $this->salesTaxId = $salesTaxId;
        $this->cdtfaThirdPartyAccessSecurityCode = $cdtfaThirdPartyAccessSecurityCode;
        $this->mfaCompleted = $mfaCompleted;
    }
}