<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** ConnecticutFields - State-specific fields for Connecticut registration import (myconneCT / DRS). */
class ConnecticutFields
{
    /**
     *
     * @var \KintsugiTax\SDK\Models\Components\ConnecticutRegistrationType $registrationType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ConnecticutRegistrationType')]
    public ConnecticutRegistrationType $registrationType;

    /**
     * Business name as registered with the state of Connecticut.
     *
     * @var string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_name')]
    public string $businessName;

    /**
     * Connecticut tax registration number issued by DRS.
     *
     * @var string $ctTaxRegistrationNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ct_tax_registration_number')]
    public string $ctTaxRegistrationNumber;

    /**
     * Last payment made to the state as a plain decimal (e.g. 0.00 if no payment has been made; do not include $ or commas).
     *
     * @var string $lastPaymentToState
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_payment_to_state')]
    public string $lastPaymentToState;

    /**
     * Connecticut DRS registration number used on the filing (AP) report; distinct from the myconneCT login credentials.
     *
     * @var ?string $registrationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $registrationId = null;

    /**
     * Whether the customer has completed MFA setup in their Connecticut tax account.
     *
     * @var ?bool $mfaCompleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mfa_completed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $mfaCompleted = null;

    /**
     * @param  \KintsugiTax\SDK\Models\Components\ConnecticutRegistrationType  $registrationType
     * @param  string  $businessName
     * @param  string  $ctTaxRegistrationNumber
     * @param  string  $lastPaymentToState
     * @param  ?bool  $mfaCompleted
     * @param  ?string  $registrationId
     * @phpstan-pure
     */
    public function __construct(ConnecticutRegistrationType $registrationType, string $businessName, string $ctTaxRegistrationNumber, string $lastPaymentToState, ?string $registrationId = null, ?bool $mfaCompleted = false)
    {
        $this->registrationType = $registrationType;
        $this->businessName = $businessName;
        $this->ctTaxRegistrationNumber = $ctTaxRegistrationNumber;
        $this->lastPaymentToState = $lastPaymentToState;
        $this->registrationId = $registrationId;
        $this->mfaCompleted = $mfaCompleted;
    }
}