<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


class CreditNoteItemCreateUpdate
{
    /**
     * Unique identifier for the credit note item in the external system.
     *
     * @var string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    public string $externalId;

    /**
     * Date when the credit note item was issued or created.
     *
     * @var \DateTime $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public \DateTime $date;

    /**
     * Unique identifier for the associated product in the external system.
     *
     * @var string $externalProductId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_product_id')]
    public string $externalProductId;

    /**
     * Brief explanation or details about the credit note item.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Pre-calculated tax amount for the item, if provided by the external system.
     *
     * @var ?float $taxAmountImported
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_amount_imported')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $taxAmountImported = null;

    /**
     * Pre-calculated tax rate for the item, if provided by the external system.
     *
     * @var ?float $taxRateImported
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_rate_imported')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $taxRateImported = null;

    /**
     * Portion of the item amount subject to taxation.
     *
     * @var ?float $taxableAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('taxable_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $taxableAmount = null;

    /**
     * This enum is used to determine if a transaction is exempt from tax.
     *
     * @var ?TaxExemptionEnum $taxExemption
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_exemption')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\TaxExemptionEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TaxExemptionEnum $taxExemption = null;

    /**
     * Detailed breakdown of individual tax components applied to this item.
     *
     * @var ?array<TaxItemBuilder> $taxItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\KintsugiTax\SDK\Models\Components\TaxItemBuilder>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $taxItems = null;

    /**
     * Number of units or amount of the product being credited.
     *
     * @var ?float $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $quantity = null;

    /**
     * Total monetary value of the credit note item before taxes.
     *
     * @var ?float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $amount = null;

    /**
     * @param  string  $externalId
     * @param  \DateTime  $date
     * @param  string  $externalProductId
     * @param  ?string  $description
     * @param  ?float  $quantity
     * @param  ?float  $amount
     * @param  ?float  $taxAmountImported
     * @param  ?float  $taxRateImported
     * @param  ?float  $taxableAmount
     * @param  ?TaxExemptionEnum  $taxExemption
     * @param  ?array<TaxItemBuilder>  $taxItems
     * @phpstan-pure
     */
    public function __construct(string $externalId, \DateTime $date, string $externalProductId, ?string $description = null, ?float $taxAmountImported = null, ?float $taxRateImported = null, ?float $taxableAmount = null, ?TaxExemptionEnum $taxExemption = null, ?array $taxItems = null, ?float $quantity = 1.0, ?float $amount = 0.00)
    {
        $this->externalId = $externalId;
        $this->date = $date;
        $this->externalProductId = $externalProductId;
        $this->description = $description;
        $this->taxAmountImported = $taxAmountImported;
        $this->taxRateImported = $taxRateImported;
        $this->taxableAmount = $taxableAmount;
        $this->taxExemption = $taxExemption;
        $this->taxItems = $taxItems;
        $this->quantity = $quantity;
        $this->amount = $amount;
    }
}