<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


class CustomerTaxRegistrationRead
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    public string $customerId;

    /**
     *
     * @var CountryCodeEnum $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country_code')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CountryCodeEnum')]
    public CountryCodeEnum $countryCode;

    /**
     * Enum for customer tax registration types.
     *
     * @var CustomerTaxTypeEnum $taxType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CustomerTaxTypeEnum')]
    public CustomerTaxTypeEnum $taxType;

    /**
     *
     * @var string $taxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_id')]
    public string $taxId;

    /**
     *
     * @var bool $isValid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_valid')]
    public bool $isValid;

    /**
     * @param  string  $id
     * @param  string  $customerId
     * @param  CountryCodeEnum  $countryCode
     * @param  CustomerTaxTypeEnum  $taxType
     * @param  string  $taxId
     * @param  bool  $isValid
     * @phpstan-pure
     */
    public function __construct(string $id, string $customerId, CountryCodeEnum $countryCode, CustomerTaxTypeEnum $taxType, string $taxId, bool $isValid)
    {
        $this->id = $id;
        $this->customerId = $customerId;
        $this->countryCode = $countryCode;
        $this->taxType = $taxType;
        $this->taxId = $taxId;
        $this->isValid = $isValid;
    }
}