<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** Enum for customer tax registration types. */
enum CustomerTaxTypeEnum: string
{
    case Gst = 'gst';
    case Hst = 'hst';
    case GstHst = 'gst_hst';
    case Qst = 'qst';
    case Pst = 'pst';
    case Rst = 'rst';
    case Vat = 'vat';
    case Unknown = 'unknown';
}
