<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


class CustomerRead
{
    /**
     * Unique identifier for the customer required.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Unique identifier for the organization associated with the customer. Required.
     *
     * @var string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public string $organizationId;

    /**
     *
     * @var ?\KintsugiTax\SDK\Models\Components\StatusEnum $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\StatusEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?StatusEnum $status = null;

    /**
     *
     * @var ?\KintsugiTax\SDK\Models\Components\AddressStatus $addressStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\AddressStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AddressStatus $addressStatus = null;

    /**
     * Customer tax registrations associated with the customer.
     *
     * @var ?array<\KintsugiTax\SDK\Models\Components\CustomerTaxRegistrationRead> $customerTaxRegistrations
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_tax_registrations')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\KintsugiTax\SDK\Models\Components\CustomerTaxRegistrationRead>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $customerTaxRegistrations = null;

    /**
     * Customer's phone number
     *
     * @var ?string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phone = null;

    /**
     * Primary street address.
     *
     * @var ?string $street1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('street_1')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $street1 = null;

    /**
     * Additional street address details, such as an apartment or suite number.
     *
     * @var ?string $street2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('street_2')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $street2 = null;

    /**
     * City where the customer resides.
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $city = null;

    /**
     * County or district of the customer.
     *
     * @var ?string $county
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('county')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $county = null;

    /**
     * State or province of the customer.
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     * ZIP or Postal code of the customer.
     *
     * @var ?string $postalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postal_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $postalCode = null;

    /**
     * Country code in ISO 3166-1 alpha-2 format
     *
     * @var ?\KintsugiTax\SDK\Models\Components\CountryCodeEnum $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CountryCodeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CountryCodeEnum $country = null;

    /**
     * Complete address string of the customer, which can be used as an alternative to individual fields.
     *
     * @var ?string $fullAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('full_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $fullAddress = null;

    /**
     * Name of the customer.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * External identifier associated with the customer.
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     * Customer's email address
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     * Registered or legal business name of the customer.
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('company_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $companyName = null;

    /**
     * Source of the customer's record.
     *
     * @var ?\KintsugiTax\SDK\Models\Components\SourceEnum $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\SourceEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SourceEnum $source = null;

    /**
     * Identifier for the connection source, if applicable.
     *
     * @var ?string $connectionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connection_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $connectionId = null;

    /**
     * Registration number of the customer.
     *
     * @var ?string $registrationNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $registrationNumber = null;

    /**
     * External friendly identifier associated with the customer. We need it for netsuite.
     *
     * @var ?string $externalFriendlyId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_friendly_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalFriendlyId = null;

    /**
     * Store name resolved from the customer's connection, if available.
     *
     * @var ?string $storeName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('store_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $storeName = null;

    /**
     * @param  string  $id
     * @param  string  $organizationId
     * @param  ?\KintsugiTax\SDK\Models\Components\StatusEnum  $status
     * @param  ?\KintsugiTax\SDK\Models\Components\AddressStatus  $addressStatus
     * @param  ?array<\KintsugiTax\SDK\Models\Components\CustomerTaxRegistrationRead>  $customerTaxRegistrations
     * @param  ?string  $phone
     * @param  ?string  $street1
     * @param  ?string  $street2
     * @param  ?string  $city
     * @param  ?string  $county
     * @param  ?string  $state
     * @param  ?string  $postalCode
     * @param  ?\KintsugiTax\SDK\Models\Components\CountryCodeEnum  $country
     * @param  ?string  $fullAddress
     * @param  ?string  $name
     * @param  ?string  $externalId
     * @param  ?string  $email
     * @param  ?string  $companyName
     * @param  ?\KintsugiTax\SDK\Models\Components\SourceEnum  $source
     * @param  ?string  $connectionId
     * @param  ?string  $registrationNumber
     * @param  ?string  $externalFriendlyId
     * @param  ?string  $storeName
     * @phpstan-pure
     */
    public function __construct(string $id, string $organizationId, ?StatusEnum $status = null, ?AddressStatus $addressStatus = null, ?array $customerTaxRegistrations = null, ?string $phone = null, ?string $street1 = null, ?string $street2 = null, ?string $city = null, ?string $county = null, ?string $state = null, ?string $postalCode = null, ?CountryCodeEnum $country = null, ?string $fullAddress = null, ?string $name = null, ?string $externalId = null, ?string $email = null, ?string $companyName = null, ?SourceEnum $source = null, ?string $connectionId = null, ?string $registrationNumber = null, ?string $externalFriendlyId = null, ?string $storeName = null)
    {
        $this->id = $id;
        $this->organizationId = $organizationId;
        $this->status = $status;
        $this->addressStatus = $addressStatus;
        $this->customerTaxRegistrations = $customerTaxRegistrations;
        $this->phone = $phone;
        $this->street1 = $street1;
        $this->street2 = $street2;
        $this->city = $city;
        $this->county = $county;
        $this->state = $state;
        $this->postalCode = $postalCode;
        $this->country = $country;
        $this->fullAddress = $fullAddress;
        $this->name = $name;
        $this->externalId = $externalId;
        $this->email = $email;
        $this->companyName = $companyName;
        $this->source = $source;
        $this->connectionId = $connectionId;
        $this->registrationNumber = $registrationNumber;
        $this->externalFriendlyId = $externalFriendlyId;
        $this->storeName = $storeName;
    }
}