<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;

use Brick\DateTime\LocalDate;
class ExemptionCreate
{
    /**
     *
     * @var ExemptionType $exemptionType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exemption_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ExemptionType')]
    public ExemptionType $exemptionType;

    /**
     * Start date for the exemption validity period (YYYY-MM-DD format)
     *
     * @var LocalDate $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_date')]
    public LocalDate $startDate;

    /**
     * Unique identifier for the customer associated with the exemption
     *
     * @var string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    public string $customerId;

    /**
     * Federal Employer Identification Number
     *
     * @var string $fein
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('FEIN')]
    public string $fein;

    /**
     * Sales tax ID for the exemption
     *
     * @var string $salesTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sales_tax_id')]
    public string $salesTaxId;

    /**
     *
     * @var ExemptionStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ExemptionStatus')]
    public ExemptionStatus $status;

    /**
     * The jurisdiction identifier for the exemption
     *
     * @var ?string $jurisdiction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('jurisdiction')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $jurisdiction = null;

    /**
     * Country code in ISO 3166-1 alpha-2 format (e.g., 'US')
     *
     * @var ?CountryCodeEnum $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country_code')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CountryCodeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CountryCodeEnum $countryCode = null;

    /**
     * End date for the exemption validity period (YYYY-MM-DD format)
     *
     * @var ?LocalDate $endDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $endDate = null;

    /**
     * Unique identifier for the transaction, if applicable
     *
     * @var ?string $transactionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transaction_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transactionId = null;

    /**
     * Indicates whether the exemption is for a reseller
     *
     * @var ?bool $reseller
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reseller')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $reseller = null;

    /**
     * @param  ExemptionType  $exemptionType
     * @param  LocalDate  $startDate
     * @param  string  $customerId
     * @param  string  $fein
     * @param  string  $salesTaxId
     * @param  ExemptionStatus  $status
     * @param  ?bool  $reseller
     * @param  ?string  $jurisdiction
     * @param  ?CountryCodeEnum  $countryCode
     * @param  ?LocalDate  $endDate
     * @param  ?string  $transactionId
     * @phpstan-pure
     */
    public function __construct(ExemptionType $exemptionType, LocalDate $startDate, string $customerId, string $fein, string $salesTaxId, ExemptionStatus $status, ?string $jurisdiction = null, ?CountryCodeEnum $countryCode = null, ?LocalDate $endDate = null, ?string $transactionId = null, ?bool $reseller = false)
    {
        $this->exemptionType = $exemptionType;
        $this->startDate = $startDate;
        $this->customerId = $customerId;
        $this->fein = $fein;
        $this->salesTaxId = $salesTaxId;
        $this->status = $status;
        $this->jurisdiction = $jurisdiction;
        $this->countryCode = $countryCode;
        $this->endDate = $endDate;
        $this->transactionId = $transactionId;
        $this->reseller = $reseller;
    }
}