<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


class ExemptionRequired
{
    /**
     * Unique identifier of the organization. This field is deprecated, and should no longer be used. The value is populated through the 'x-organization-id' header.
     *
     * @var string $organizationId
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public string $organizationId;

    /**
     *
     * @var ExemptionType $exemptionType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exemption_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ExemptionType')]
    public ExemptionType $exemptionType;

    /**
     *
     * @var \DateTime $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_date')]
    public \DateTime $startDate;

    /**
     *
     * @var ExemptionStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ExemptionStatus')]
    public ExemptionStatus $status;

    /**
     *
     * @var bool $reseller
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reseller')]
    public bool $reseller;

    /**
     *
     * @var ?string $jurisdiction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('jurisdiction')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $jurisdiction = null;

    /**
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     * @param  string  $organizationId
     * @param  ExemptionType  $exemptionType
     * @param  \DateTime  $startDate
     * @param  ExemptionStatus  $status
     * @param  bool  $reseller
     * @param  ?string  $jurisdiction
     * @param  ?string  $customerId
     * @phpstan-pure
     */
    public function __construct(string $organizationId, ExemptionType $exemptionType, \DateTime $startDate, ExemptionStatus $status, bool $reseller, ?string $jurisdiction = null, ?string $customerId = null)
    {
        $this->organizationId = $organizationId;
        $this->exemptionType = $exemptionType;
        $this->startDate = $startDate;
        $this->status = $status;
        $this->reseller = $reseller;
        $this->jurisdiction = $jurisdiction;
        $this->customerId = $customerId;
    }
}