<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


enum FilingStatusEnum: string
{
    case Unfiled = 'UNFILED';
    case Filed = 'FILED';
    case Filing = 'FILING';
}
