<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;

use Brick\DateTime\LocalDate;
class FilingDetailsRead
{
    /**
     * The start date of the filing period.
     *
     * @var LocalDate $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_date')]
    public LocalDate $startDate;

    /**
     * The end date of the filing period.
     *
     * @var LocalDate $endDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_date')]
    public LocalDate $endDate;

    /**
     *
     * @var CountryCodeEnum $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country_code')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CountryCodeEnum')]
    public CountryCodeEnum $countryCode;

    /**
     * Unique identifier for the filing.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Identifier for the registration associated with the filing.
     *
     * @var string $registrationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_id')]
    public string $registrationId;

    /**
     *
     * @var ?FilingStatusEnum $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\FilingStatusEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FilingStatusEnum $status = null;

    /**
     * The due date of the filing.
     *
     * @var ?string $dueDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('due_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $dueDate = null;

    /**
     * The date the filing was completed, if applicable.
     *
     * @var ?string $dateFiled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date_filed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $dateFiled = null;

    /**
     * Indicates if the filing was done manually.
     *
     * @var ?bool $isManual
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_manual')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isManual = null;

    /**
     * The code of the state associated with the filing (e.g., IA, NY).
     *
     * @var ?string $stateCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $stateCode = null;

    /**
     * The name of the state associated with the filing
     *
     *         (e.g., Iowa, New York).
     *
     * @var ?string $stateName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $stateName = null;

    /**
     * The associated JIRA issue key for tracking the filing,
     *
     *         if available. Can be null.
     *
     * @var ?string $jiraIssueKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('jira_issue_key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $jiraIssueKey = null;

    /**
     * Notes or comments related to the filing.
     *
     * @var ?string $internalNotes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('internal_notes')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $internalNotes = null;

    /**
     *
     * @var ?string $recentDetailsReportLink
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recent_details_report_link')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $recentDetailsReportLink = null;

    /**
     * Return confirmation ID, if applicable.
     *
     * @var ?string $returnConfirmationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('return_confirmation_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $returnConfirmationId = null;

    /**
     * Payment confirmation ID, if applicable.
     *
     * @var ?string $paymentConfirmationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_confirmation_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $paymentConfirmationId = null;

    /**
     * Indicates if the filing can be approved.
     *
     * @var ?bool $blockApproval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('block_approval')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $blockApproval = null;

    /**
     *
     * @var ?CurrencyEnum $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CurrencyEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CurrencyEnum $currency = null;

    /**
     * Indicates the date when filing will be unpaused.
     *
     * @var ?string $pausedUntilDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paused_until_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $pausedUntilDate = null;

    /**
     * List of attachments associated with the filing, if any.
     *
     * @var ?Attachments $attachments
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attachments')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\Attachments|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Attachments $attachments = null;

    /**
     * Indicates if the filing was auto-approved. Defaults to false.
     *
     * @var ?bool $autoApproved
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('auto_approved')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $autoApproved = null;

    /**
     * The calculated amount for the filing. Defaults to 0.00.
     *
     * @var ?string $amountCalculated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_calculated')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $amountCalculated = null;

    /**
     * Adjusted amount, if any.
     *
     * @var ?string $amountAdjusted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_adjusted')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $amountAdjusted = null;

    /**
     * Discounts applied to the filing.
     *
     * @var ?string $amountDiscounts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_discounts')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $amountDiscounts = null;

    /**
     * Discounts applied to the amount.
     *
     * @var ?string $amountFees
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_fees')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $amountFees = null;

    /**
     * Penalties applied to the filing.
     *
     * @var ?string $amountPenalties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_penalties')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $amountPenalties = null;

    /**
     * Total tax collected during the filing period.
     *
     * @var ?string $amountTaxCollected
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_tax_collected')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $amountTaxCollected = null;

    /**
     * Total sales amount during the filing period.
     *
     * @var ?string $amountSales
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_sales')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $amountSales = null;

    /**
     * Total taxable amount during the filing period.
     *
     * @var ?string $totalTaxableSales
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_taxable_sales')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $totalTaxableSales = null;

    /**
     * Final amount due for the filing.
     *
     * @var ?string $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $amount = null;

    /**
     * Total tax liability for the filing.
     *
     * @var ?string $totalTaxLiability
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_tax_liability')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $totalTaxLiability = null;

    /**
     * Total number of transactions associated with the filing.
     *
     * @var ?int $transactionCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transaction_count')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $transactionCount = null;

    /**
     * The amount of tax remitted.
     *
     * @var ?string $taxRemitted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_remitted')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxRemitted = null;

    /**
     *
     * @var ?string $creditsUtilized
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('credits_utilized')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $creditsUtilized = null;

    /**
     * @param  LocalDate  $startDate
     * @param  LocalDate  $endDate
     * @param  CountryCodeEnum  $countryCode
     * @param  string  $id
     * @param  string  $registrationId
     * @param  ?FilingStatusEnum  $status
     * @param  ?string  $dueDate
     * @param  ?string  $dateFiled
     * @param  ?bool  $isManual
     * @param  ?string  $stateCode
     * @param  ?string  $stateName
     * @param  ?string  $jiraIssueKey
     * @param  ?bool  $autoApproved
     * @param  ?string  $amountCalculated
     * @param  ?string  $amountAdjusted
     * @param  ?string  $amountDiscounts
     * @param  ?string  $amountFees
     * @param  ?string  $amountPenalties
     * @param  ?string  $amountTaxCollected
     * @param  ?string  $amountSales
     * @param  ?string  $totalTaxableSales
     * @param  ?string  $amount
     * @param  ?string  $totalTaxLiability
     * @param  ?int  $transactionCount
     * @param  ?string  $internalNotes
     * @param  ?string  $recentDetailsReportLink
     * @param  ?string  $taxRemitted
     * @param  ?string  $returnConfirmationId
     * @param  ?string  $paymentConfirmationId
     * @param  ?bool  $blockApproval
     * @param  ?CurrencyEnum  $currency
     * @param  ?string  $pausedUntilDate
     * @param  ?Attachments  $attachments
     * @param  ?string  $creditsUtilized
     * @phpstan-pure
     */
    public function __construct(LocalDate $startDate, LocalDate $endDate, CountryCodeEnum $countryCode, string $id, string $registrationId, ?FilingStatusEnum $status = null, ?string $dueDate = null, ?string $dateFiled = null, ?bool $isManual = null, ?string $stateCode = null, ?string $stateName = null, ?string $jiraIssueKey = null, ?string $internalNotes = null, ?string $recentDetailsReportLink = null, ?string $returnConfirmationId = null, ?string $paymentConfirmationId = null, ?bool $blockApproval = null, ?CurrencyEnum $currency = null, ?string $pausedUntilDate = null, ?Attachments $attachments = null, ?bool $autoApproved = false, ?string $amountCalculated = '0.00', ?string $amountAdjusted = '0.00', ?string $amountDiscounts = '0.00', ?string $amountFees = '0.00', ?string $amountPenalties = '0.00', ?string $amountTaxCollected = '0.00', ?string $amountSales = '0.00', ?string $totalTaxableSales = '0.00', ?string $amount = '0.00', ?string $totalTaxLiability = '0.00', ?int $transactionCount = 0, ?string $taxRemitted = '0.00', ?string $creditsUtilized = '0.00')
    {
        $this->startDate = $startDate;
        $this->endDate = $endDate;
        $this->countryCode = $countryCode;
        $this->id = $id;
        $this->registrationId = $registrationId;
        $this->status = $status;
        $this->dueDate = $dueDate;
        $this->dateFiled = $dateFiled;
        $this->isManual = $isManual;
        $this->stateCode = $stateCode;
        $this->stateName = $stateName;
        $this->jiraIssueKey = $jiraIssueKey;
        $this->internalNotes = $internalNotes;
        $this->recentDetailsReportLink = $recentDetailsReportLink;
        $this->returnConfirmationId = $returnConfirmationId;
        $this->paymentConfirmationId = $paymentConfirmationId;
        $this->blockApproval = $blockApproval;
        $this->currency = $currency;
        $this->pausedUntilDate = $pausedUntilDate;
        $this->attachments = $attachments;
        $this->autoApproved = $autoApproved;
        $this->amountCalculated = $amountCalculated;
        $this->amountAdjusted = $amountAdjusted;
        $this->amountDiscounts = $amountDiscounts;
        $this->amountFees = $amountFees;
        $this->amountPenalties = $amountPenalties;
        $this->amountTaxCollected = $amountTaxCollected;
        $this->amountSales = $amountSales;
        $this->totalTaxableSales = $totalTaxableSales;
        $this->amount = $amount;
        $this->totalTaxLiability = $totalTaxLiability;
        $this->transactionCount = $transactionCount;
        $this->taxRemitted = $taxRemitted;
        $this->creditsUtilized = $creditsUtilized;
    }
}