<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


enum HawaiiRegistrationType: string
{
    case GeneralExciseTax = 'GENERAL_EXCISE_TAX';
}
