<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** Louisiana license type, which determines the filing portal: Direct Marketers file using the Louisiana DOR LaTAP website, Remote Sellers file using the Remote Sellers website, and Standard license types file using the Parish E-File website. */
enum LicenseType: string
{
    case DirectMarketer = 'DIRECT_MARKETER';
    case RemoteSeller = 'REMOTE_SELLER';
    case Standard = 'STANDARD';
}
