<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** MarylandFields - State-specific fields for Maryland Tax Connect registration import. */
class MarylandFields
{
    /**
     * State-registered business name as shown in Maryland Tax Connect.
     *
     * @var string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_name')]
    public string $businessName;

    /**
     * Maryland state-issued tax identification number (MD State Tax ID).
     *
     * @var string $mdStateTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('md_state_tax_id')]
    public string $mdStateTaxId;

    /**
     * Whether the business is a marketplace facilitator.
     *
     * @var bool $marketplaceFacilitator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('marketplace_facilitator')]
    public bool $marketplaceFacilitator;

    /**
     * Registration type for this Maryland import: sales and use tax.
     *
     * @var string $registrationType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_type')]
    public string $registrationType;

    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Maryland tax account.
     *
     * @var ?bool $mfaCompleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mfa_completed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $mfaCompleted = null;

    /**
     * @param  string  $registrationType
     * @param  string  $businessName
     * @param  string  $mdStateTaxId
     * @param  bool  $marketplaceFacilitator
     * @param  ?bool  $mfaCompleted
     * @phpstan-pure
     */
    public function __construct(string $businessName, string $mdStateTaxId, bool $marketplaceFacilitator, string $registrationType = 'SALES_AND_USE_TAX', ?bool $mfaCompleted = false)
    {
        $this->businessName = $businessName;
        $this->mdStateTaxId = $mdStateTaxId;
        $this->marketplaceFacilitator = $marketplaceFacilitator;
        $this->registrationType = $registrationType;
        $this->mfaCompleted = $mfaCompleted;
    }
}