<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


enum NexusTypeEnum: string
{
    case CanadaFederal = 'CANADA_FEDERAL';
    case EuAggregator = 'EU_AGGREGATOR';
    case State = 'STATE';
    case EuMemberState = 'EU_MEMBER_STATE';
}
