<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


enum NexusStateEnum: string
{
    case Exposed = 'EXPOSED';
    case Approaching = 'APPROACHING';
    case PendingRegistration = 'PENDING_REGISTRATION';
    case OssPendingRegistration = 'OSS_PENDING_REGISTRATION';
    case Registered = 'REGISTERED';
    case OssRegistered = 'OSS_REGISTERED';
    case NotExposed = 'NOT_EXPOSED';
}
