<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** OklahomaFields - State-specific fields for Oklahoma OkTAP portal registration import. */
class OklahomaFields
{
    /**
     * Registration type for this Oklahoma import: sales tax or remote seller.
     *
     * @var \KintsugiTax\SDK\Models\Components\OklahomaFieldsRegistrationType $registrationType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\OklahomaFieldsRegistrationType')]
    public OklahomaFieldsRegistrationType $registrationType;

    /**
     * State-registered business name as shown in OkTAP.
     *
     * @var string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_name')]
    public string $businessName;

    /**
     * Oklahoma state-issued tax identification number (OK State Tax ID).
     *
     * @var string $okStateTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ok_state_tax_id')]
    public string $okStateTaxId;

    /**
     * ZIP or Canadian postal code for the address used when registering with the state. Accepts a 5-digit US ZIP or a Canadian postal code (e.g. L6H0C3).
     *
     * @var string $zipCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('zip_code')]
    public string $zipCode;

    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Oklahoma OkTAP account.
     *
     * @var ?bool $mfaCompleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mfa_completed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $mfaCompleted = null;

    /**
     * @param  \KintsugiTax\SDK\Models\Components\OklahomaFieldsRegistrationType  $registrationType
     * @param  string  $businessName
     * @param  string  $okStateTaxId
     * @param  string  $zipCode
     * @param  ?bool  $mfaCompleted
     * @phpstan-pure
     */
    public function __construct(OklahomaFieldsRegistrationType $registrationType, string $businessName, string $okStateTaxId, string $zipCode, ?bool $mfaCompleted = false)
    {
        $this->registrationType = $registrationType;
        $this->businessName = $businessName;
        $this->okStateTaxId = $okStateTaxId;
        $this->zipCode = $zipCode;
        $this->mfaCompleted = $mfaCompleted;
    }
}