<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


class PageProductRead
{
    /**
     * $items
     *
     * @var array<ProductRead> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\KintsugiTax\SDK\Models\Components\ProductRead>')]
    public array $items;

    /**
     *
     * @var ?int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public ?int $total;

    /**
     *
     * @var ?int $page
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('page')]
    public ?int $page;

    /**
     *
     * @var ?int $size
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('size')]
    public ?int $size;

    /**
     *
     * @var ?int $pages
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pages')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $pages = null;

    /**
     * @param  array<ProductRead>  $items
     * @param  ?int  $total
     * @param  ?int  $page
     * @param  ?int  $size
     * @param  ?int  $pages
     * @phpstan-pure
     */
    public function __construct(array $items, ?int $total = null, ?int $page = null, ?int $size = null, ?int $pages = null)
    {
        $this->items = $items;
        $this->total = $total;
        $this->page = $page;
        $this->size = $size;
        $this->pages = $pages;
    }
}