<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/**
 * Account validation methods offered by Pennsylvania myPATH third-party access.
 *
 *
 * The requester proves ownership with exactly one of these: a Letter ID, a Business
 * Registration Confirmation Code, a Payment Amount, or a Return Line Item.
 */
enum PennsylvaniaAccountValidationMethod: string
{
    case LetterId = 'LETTER_ID';
    case BusinessRegistrationConfirmationCode = 'BUSINESS_REGISTRATION_CONFIRMATION_CODE';
    case PaymentAmount = 'PAYMENT_AMOUNT';
    case ReturnLineItem = 'RETURN_LINE_ITEM';
}
