<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


enum PeriodModelEnum: string
{
    case CurrentOrPrevious = 'CURRENT_OR_PREVIOUS';
    case PrecedingYearFromOctober = 'PRECEDING_YEAR_FROM_OCTOBER';
    case CalendarYear = 'CALENDAR_YEAR';
    case Previous12Months = 'PREVIOUS_12_MONTHS';
    case Previous4Quarters = 'PREVIOUS_4_QUARTERS';
    case Previous4QuartersOffset = 'PREVIOUS_4_QUARTERS_OFFSET';
    case PrecedingYear = 'PRECEDING_YEAR';
    case PrecedingYearQuarterly = 'PRECEDING_YEAR_QUARTERLY';
    case PrecedingYearQuarterlyOffset = 'PRECEDING_YEAR_QUARTERLY_OFFSET';
}
