<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;

use Brick\DateTime\LocalDate;
class PhysicalNexusCreate
{
    /**
     *
     * @var CountryCodeEnum $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country_code')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CountryCodeEnum')]
    public CountryCodeEnum $countryCode;

    /**
     * The state or province code in
     *
     *                             ISO 3166-2 format (e.g., CA).
     *
     * @var string $stateCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state_code')]
    public string $stateCode;

    /**
     * The date when the nexus became
     *
     *                             effective (YYYY-MM-DD).
     *
     * @var LocalDate $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_date')]
    public LocalDate $startDate;

    /**
     *
     * @var PhysicalNexusCategory $category
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('category')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\PhysicalNexusCategory')]
    public PhysicalNexusCategory $category;

    /**
     * The date when the
     *
     *                                         nexus ended, if applicable.
     *
     * @var ?string $endDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $endDate = null;

    /**
     * Optional
     *
     *                                         external identifier for the nexus.
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     *
     * @var ?PhysicalNexusSource $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\PhysicalNexusSource|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PhysicalNexusSource $source = null;

    /**
     * @param  CountryCodeEnum  $countryCode
     * @param  string  $stateCode
     * @param  LocalDate  $startDate
     * @param  PhysicalNexusCategory  $category
     * @param  ?string  $endDate
     * @param  ?string  $externalId
     * @param  ?PhysicalNexusSource  $source
     * @phpstan-pure
     */
    public function __construct(CountryCodeEnum $countryCode, string $stateCode, LocalDate $startDate, PhysicalNexusCategory $category, ?string $endDate = null, ?string $externalId = null, ?PhysicalNexusSource $source = null)
    {
        $this->countryCode = $countryCode;
        $this->stateCode = $stateCode;
        $this->startDate = $startDate;
        $this->category = $category;
        $this->endDate = $endDate;
        $this->externalId = $externalId;
        $this->source = $source;
    }
}