<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


enum PhysicalNexusSource: string
{
    case User = 'USER';
    case Deel = 'DEEL';
}
