<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;

use Brick\DateTime\LocalDate;
class PhysicalNexusUpdate
{
    /**
     * The date when the nexus became
     *
     *                                 effective (YYYY-MM-DD).
     *
     * @var LocalDate $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_date')]
    public LocalDate $startDate;

    /**
     *
     * @var PhysicalNexusCategory $category
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('category')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\PhysicalNexusCategory')]
    public PhysicalNexusCategory $category;

    /**
     * The date when the
     *
     *                                         nexus ends, if applicable (YYYY-MM-DD).
     *
     * @var ?string $endDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $endDate = null;

    /**
     * @param  LocalDate  $startDate
     * @param  PhysicalNexusCategory  $category
     * @param  ?string  $endDate
     * @phpstan-pure
     */
    public function __construct(LocalDate $startDate, PhysicalNexusCategory $category, ?string $endDate = null)
    {
        $this->startDate = $startDate;
        $this->category = $category;
        $this->endDate = $endDate;
    }
}