<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


class ProductRead
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    public string $externalId;

    /**
     * $sku
     *
     * @var array<string> $sku
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sku')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $sku;

    /**
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     *
     * @var ProductStatusEnum $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ProductStatusEnum')]
    public ProductStatusEnum $status;

    /**
     *
     * @var string $productCategory
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_category')]
    public string $productCategory;

    /**
     *
     * @var string $productSubcategory
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_subcategory')]
    public string $productSubcategory;

    /**
     *
     * @var bool $taxExempt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_exempt')]
    public bool $taxExempt;

    /**
     *
     * @var SourceEnum $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\SourceEnum')]
    public SourceEnum $source;

    /**
     *
     * @var string $connectionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connection_id')]
    public string $connectionId;

    /**
     *
     * @var bool $classificationFailed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('classification_failed')]
    public bool $classificationFailed;

    /**
     * @param  string  $id
     * @param  string  $externalId
     * @param  array<string>  $sku
     * @param  string  $code
     * @param  string  $name
     * @param  string  $description
     * @param  ProductStatusEnum  $status
     * @param  string  $productCategory
     * @param  string  $productSubcategory
     * @param  bool  $taxExempt
     * @param  SourceEnum  $source
     * @param  string  $connectionId
     * @param  bool  $classificationFailed
     * @phpstan-pure
     */
    public function __construct(string $id, string $externalId, array $sku, string $code, string $name, string $description, ProductStatusEnum $status, string $productCategory, string $productSubcategory, bool $taxExempt, SourceEnum $source, string $connectionId, bool $classificationFailed)
    {
        $this->id = $id;
        $this->externalId = $externalId;
        $this->sku = $sku;
        $this->code = $code;
        $this->name = $name;
        $this->description = $description;
        $this->status = $status;
        $this->productCategory = $productCategory;
        $this->productSubcategory = $productSubcategory;
        $this->taxExempt = $taxExempt;
        $this->source = $source;
        $this->connectionId = $connectionId;
        $this->classificationFailed = $classificationFailed;
    }
}