<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


enum ProductCategoryEnum: string
{
    case Physical = 'PHYSICAL';
    case Digital = 'DIGITAL';
    case Service = 'SERVICE';
    case Unknown = 'UNKNOWN';
    case Miscellaneous = 'MISCELLANEOUS';
}
