<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


enum ProductSubCategoryEnum: string
{
    case Unknown = 'UNKNOWN';
    case Saas = 'SAAS';
    case DigitalGeneral = 'DIGITAL_GENERAL';
    case B2BSaas = 'B2B_SAAS';
    case SoftwareOnPersonalProperty = 'SOFTWARE_ON_PERSONAL_PROPERTY';
    case SoftwareDownloaded = 'SOFTWARE_DOWNLOADED';
    case CustomSoftwareOnPersonalProperty = 'CUSTOM_SOFTWARE_ON_PERSONAL_PROPERTY';
    case CustomSoftwareDownloaded = 'CUSTOM_SOFTWARE_DOWNLOADED';
    case CustomizationOfSoftware = 'CUSTOMIZATION_OF_SOFTWARE';
    case B2CSaas = 'B2C_SAAS';
    case Iaas = 'IAAS';
    case ServiceGeneral = 'SERVICE_GENERAL';
    case ProfessionalService = 'PROFESSIONAL_SERVICE';
    case TangiblePropertyService = 'TANGIBLE_PROPERTY_SERVICE';
    case RealPropertyService = 'REAL_PROPERTY_SERVICE';
    case BusinessService = 'BUSINESS_SERVICE';
    case PersonalService = 'PERSONAL_SERVICE';
    case AmusementService = 'AMUSEMENT_SERVICE';
    case MedicalServices = 'MEDICAL_SERVICES';
    case SecurityServicesElectronicMonitoring = 'SECURITY_SERVICES_ELECTRONIC_MONITORING';
    case FacilityMaintenanceRealPropertyLaborOnly = 'FACILITY_MAINTENANCE_REAL_PROPERTY_LABOR_ONLY';
    case CommercialRenovationCapitalImprovementLabor = 'COMMERCIAL_RENOVATION_CAPITAL_IMPROVEMENT_LABOR';
    case CommercialConstructionExistingBuildingsLabor = 'COMMERCIAL_CONSTRUCTION_EXISTING_BUILDINGS_LABOR';
    case PhysicalGeneral = 'PHYSICAL_GENERAL';
    case GeneralClothing = 'GENERAL_CLOTHING';
    case Catering = 'CATERING';
    case GroceryFood = 'GROCERY_FOOD';
    case LeasesAndRentalsMotorVehicles = 'LEASES_AND_RENTALS_MOTOR_VEHICLES';
    case LeasesAndRentalsTangibleMediaProperty = 'LEASES_AND_RENTALS_TANGIBLE_MEDIA_PROPERTY';
    case Machinery = 'MACHINERY';
    case RawMaterials = 'RAW_MATERIALS';
    case UtilitiesFuel = 'UTILITIES_FUEL';
    case MedicalDevices = 'MEDICAL_DEVICES';
    case Medicines = 'MEDICINES';
    case Newspapers = 'NEWSPAPERS';
    case Periodicals = 'PERIODICALS';
    case GeneralOccasionalSales = 'GENERAL_OCCASIONAL_SALES';
    case MotorVehiclesOccasionalSales = 'MOTOR_VEHICLES_OCCASIONAL_SALES';
    case GeneralOptionalMaintenanceContracts = 'GENERAL_OPTIONAL_MAINTENANCE_CONTRACTS';
    case PartsPurchasedOptionalMaintenanceContracts = 'PARTS_PURCHASED_OPTIONAL_MAINTENANCE_CONTRACTS';
    case GeneralPollutionControlEquipment = 'GENERAL_POLLUTION_CONTROL_EQUIPMENT';
    case GeneralTradeIns = 'GENERAL_TRADE_INS';
    case FoodVendingMachine = 'FOOD_VENDING_MACHINE';
    case MerchandiseVendingMachine = 'MERCHANDISE_VENDING_MACHINE';
    case Supplements = 'SUPPLEMENTS';
    case FeminineHygiene = 'FEMININE_HYGIENE';
    case OralHygiene = 'ORAL_HYGIENE';
    case BeverageNutritionLabelEnergyShotsAndDrinks = 'BEVERAGE_NUTRITION_LABEL_ENERGY_SHOTS_AND_DRINKS';
    case DietarySupplementsSupplementFactsLabelRetail = 'DIETARY_SUPPLEMENTS_SUPPLEMENT_FACTS_LABEL_RETAIL';
    case AdvertisingMediaInsertDistributedByNewspaper = 'ADVERTISING_MEDIA_INSERT_DISTRIBUTED_BY_NEWSPAPER';
    case AdvertisingMediaInsertDistributedByMailPackage = 'ADVERTISING_MEDIA_INSERT_DISTRIBUTED_BY_MAIL_PACKAGE';
    case MaintenanceServicesMaterials = 'MAINTENANCE_SERVICES_MATERIALS';
    case NutritionBars = 'NUTRITION_BARS';
    case Shipping = 'SHIPPING';
    case GiftCard = 'GIFT_CARD';
    case CreditCardSurcharges = 'CREDIT_CARD_SURCHARGES';
    case CreditCardFees = 'CREDIT_CARD_FEES';
    case MiscellaneousExempt = 'MISCELLANEOUS_EXEMPT';
    case Discount = 'DISCOUNT';
    case GiftWrapping = 'GIFT_WRAPPING';
    case Handling = 'HANDLING';
    case Tax = 'TAX';
    case DanceLessons = 'DANCE_LESSONS';
}
