<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


class ProductRead
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    public string $externalId;

    /**
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var \KintsugiTax\SDK\Models\Components\ProductStatusEnum $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ProductStatusEnum')]
    public ProductStatusEnum $status;

    /**
     * Main category of the product.
     *
     *         For example, Physical, Digital, etc. You can
     *         retrieve supported categories from [GET /products/categories endpoint](/reference/api/products/get-product-categories)
     *
     * @var string $productCategory
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_category')]
    public string $productCategory;

    /**
     * Subcategory of the product.
     *
     *         For example, General Clothing, UNKNOWN, etc. You can
     *         retrieve supported subcategories from [GET /products/categories endpoint](/reference/api/products/get-product-categories)
     *
     * @var string $productSubcategory
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_subcategory')]
    public string $productSubcategory;

    /**
     *
     * @var bool $taxExempt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_exempt')]
    public bool $taxExempt;

    /**
     *
     * @var \KintsugiTax\SDK\Models\Components\SourceEnum $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\SourceEnum')]
    public SourceEnum $source;

    /**
     * $sku
     *
     * @var ?array<string> $sku
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sku')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    public ?array $sku;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public ?string $description;

    /**
     *
     * @var ?string $connectionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connection_id')]
    public ?string $connectionId;

    /**
     *
     * @var ?bool $classificationFailed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('classification_failed')]
    public ?bool $classificationFailed;

    /**
     *
     * @var ?string $storeName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('store_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $storeName = null;

    /**
     *
     * @var ?string $sourceTaxonomyType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_taxonomy_type')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceTaxonomyType = null;

    /**
     *
     * @var ?string $sourceTaxonomyCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_taxonomy_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceTaxonomyCode = null;

    /**
     *
     * @var ?string $sourceTaxonomyId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_taxonomy_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceTaxonomyId = null;

    /**
     *
     * @var ?string $sourceTaxonomyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_taxonomy_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceTaxonomyName = null;

    /**
     * $sourceTaxonomyCategories
     *
     * @var ?array<array<string, mixed>> $sourceTaxonomyCategories
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_taxonomy_categories')]
    #[\Speakeasy\Serializer\Annotation\Type('array<array<string, mixed>>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $sourceTaxonomyCategories = null;

    /**
     * $sourceTaxonomyMetadata
     *
     * @var ?array<string, mixed> $sourceTaxonomyMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_taxonomy_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $sourceTaxonomyMetadata = null;

    /**
     * @param  string  $id
     * @param  string  $externalId
     * @param  string  $code
     * @param  string  $name
     * @param  \KintsugiTax\SDK\Models\Components\ProductStatusEnum  $status
     * @param  string  $productCategory
     * @param  string  $productSubcategory
     * @param  bool  $taxExempt
     * @param  \KintsugiTax\SDK\Models\Components\SourceEnum  $source
     * @param  ?array<string>  $sku
     * @param  ?string  $description
     * @param  ?string  $connectionId
     * @param  ?bool  $classificationFailed
     * @param  ?string  $storeName
     * @param  ?string  $sourceTaxonomyType
     * @param  ?string  $sourceTaxonomyCode
     * @param  ?string  $sourceTaxonomyId
     * @param  ?string  $sourceTaxonomyName
     * @param  ?array<array<string, mixed>>  $sourceTaxonomyCategories
     * @param  ?array<string, mixed>  $sourceTaxonomyMetadata
     * @phpstan-pure
     */
    public function __construct(string $id, string $externalId, string $code, string $name, ProductStatusEnum $status, string $productCategory, string $productSubcategory, bool $taxExempt, SourceEnum $source, ?array $sku = null, ?string $description = null, ?string $connectionId = null, ?bool $classificationFailed = null, ?string $storeName = null, ?string $sourceTaxonomyType = null, ?string $sourceTaxonomyCode = null, ?string $sourceTaxonomyId = null, ?string $sourceTaxonomyName = null, ?array $sourceTaxonomyCategories = null, ?array $sourceTaxonomyMetadata = null)
    {
        $this->id = $id;
        $this->externalId = $externalId;
        $this->code = $code;
        $this->name = $name;
        $this->status = $status;
        $this->productCategory = $productCategory;
        $this->productSubcategory = $productSubcategory;
        $this->taxExempt = $taxExempt;
        $this->source = $source;
        $this->sku = $sku;
        $this->description = $description;
        $this->connectionId = $connectionId;
        $this->classificationFailed = $classificationFailed;
        $this->storeName = $storeName;
        $this->sourceTaxonomyType = $sourceTaxonomyType;
        $this->sourceTaxonomyCode = $sourceTaxonomyCode;
        $this->sourceTaxonomyId = $sourceTaxonomyId;
        $this->sourceTaxonomyName = $sourceTaxonomyName;
        $this->sourceTaxonomyCategories = $sourceTaxonomyCategories;
        $this->sourceTaxonomyMetadata = $sourceTaxonomyMetadata;
    }
}