<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** RegistrationJurisdictionOptionRead - One distinct (country, state) jurisdiction for listings and filters. */
class RegistrationJurisdictionOptionRead
{
    /**
     * ISO 3166-1 alpha-2 country code (e.g. US, DE).
     *
     * @var string $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country_code')]
    public string $countryCode;

    /**
     * State or province code (may be empty for country-level rows).
     *
     * @var string $stateCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state_code')]
    public string $stateCode;

    /**
     * Display name for the state or province.
     *
     * @var string $stateName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state_name')]
    public string $stateName;

    /**
     * @param  string  $countryCode
     * @param  string  $stateCode
     * @param  string  $stateName
     * @phpstan-pure
     */
    public function __construct(string $countryCode, string $stateCode, string $stateName)
    {
        $this->countryCode = $countryCode;
        $this->stateCode = $stateCode;
        $this->stateName = $stateName;
    }
}