<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;

use Brick\DateTime\LocalDate;
class RegistrationUpdateAPI
{
    /**
     * The date when the registration was created. Format: YYYY-MM-DD.
     *
     * @var ?LocalDate $registrationDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $registrationDate = null;

    /**
     * Email address associated with the registration.
     *
     * @var ?string $registrationEmail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $registrationEmail = null;

    /**
     * Timestamp when the registration was requested.
     *
     * @var ?\DateTime $registrationRequested
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_requested')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $registrationRequested = null;

    /**
     * Timestamp when the registration was completed.
     *
     * @var ?\DateTime $registrationCompleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_completed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $registrationCompleted = null;

    /**
     * Timestamp when deregistration was requested.
     *
     * @var ?\DateTime $deregistrationRequested
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deregistration_requested')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $deregistrationRequested = null;

    /**
     * Timestamp when the deregistration was completed.
     *
     * @var ?\DateTime $deregistrationCompleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deregistration_completed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $deregistrationCompleted = null;

    /**
     * Indicates whether the registration was completed automatically.
     *
     * @var ?bool $autoRegistered
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('auto_registered')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $autoRegistered = null;

    /**
     * The tax registration regime (e.g., STANDARD, SIMPLIFIED).
     *
     * @var ?\KintsugiTax\SDK\Models\Components\RegistrationsRegimeEnum $registrationsRegime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registrations_regime')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\RegistrationsRegimeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RegistrationsRegimeEnum $registrationsRegime = null;

    /**
     *
     * @var ?\KintsugiTax\SDK\Models\Components\ChangeRegimeStatusEnum $changeRegimeStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('change_regime_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ChangeRegimeStatusEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ChangeRegimeStatusEnum $changeRegimeStatus = null;

    /**
     * Indicates whether third-party access is enabled for this registration.
     *
     * @var ?bool $thirdPartyEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('third_party_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $thirdPartyEnabled = null;

    /**
     * Indicates whether two-factor authentication (2FA) is enabled for this registration.
     *
     * @var ?bool $twoFactorEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('two_factor_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $twoFactorEnabled = null;

    /**
     * Indicates whether the  registration is marked as collecting in shopify
     *
     * @var ?bool $markedCollecting
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('marked_collecting')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $markedCollecting = null;

    /**
     * The encrypted username for the registration.
     *
     * @var ?string $encryptedUsername
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('encrypted_username')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $encryptedUsername = null;

    /**
     * The username associated with the registration.
     *
     * @var ?string $username
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('username')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $username = null;

    /**
     * The updated filing frequency (MONTHLY, QUARTERLY, etc.).
     *
     * @var ?\KintsugiTax\SDK\Models\Components\FilingFrequencyEnum $filingFrequency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('filing_frequency')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\FilingFrequencyEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FilingFrequencyEnum $filingFrequency = null;

    /**
     * The updated date from which filings should start (YYYY-MM-DD).
     *
     * @var ?LocalDate $createFilingsFrom
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('create_filings_from')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $createFilingsFrom = null;

    /**
     * Indicates whether the registration is approaching an action (e.g., renewal).
     *
     * @var ?bool $isApproaching
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_approaching')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isApproaching = null;

    /**
     * Additional notes or comments related to the registration.
     *
     * @var ?string $comment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('comment')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $comment = null;

    /**
     * Indicates if the Voluntary Disclosure Agreement (VDA) applies.
     *
     * @var ?bool $vda
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('vda')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $vda = null;

    /**
     * Organization-level tax ID (e.g., VAT number, Canada Business Number).
     *
     * @var ?string $taxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxId = null;

    /**
     * The Importer of Record (IOR) number for the registration.
     *
     * @var ?string $iorNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ior_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $iorNumber = null;

    /**
     * If true, do not file for this registration (treated as False by default).
     *
     * @var ?bool $doNotFile
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('do_not_file')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $doNotFile = null;

    /**
     * Whether to also file the single period preceding the first filing period.
     *
     * @var ?bool $createBackFiling
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('create_back_filing')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $createBackFiling = null;

    /**
     * @param  ?bool  $doNotFile
     * @param  ?bool  $createBackFiling
     * @param  ?LocalDate  $registrationDate
     * @param  ?string  $registrationEmail
     * @param  ?\DateTime  $registrationRequested
     * @param  ?\DateTime  $registrationCompleted
     * @param  ?\DateTime  $deregistrationRequested
     * @param  ?\DateTime  $deregistrationCompleted
     * @param  ?bool  $autoRegistered
     * @param  ?\KintsugiTax\SDK\Models\Components\RegistrationsRegimeEnum  $registrationsRegime
     * @param  ?\KintsugiTax\SDK\Models\Components\ChangeRegimeStatusEnum  $changeRegimeStatus
     * @param  ?bool  $thirdPartyEnabled
     * @param  ?bool  $twoFactorEnabled
     * @param  ?bool  $markedCollecting
     * @param  ?string  $encryptedUsername
     * @param  ?string  $username
     * @param  ?\KintsugiTax\SDK\Models\Components\FilingFrequencyEnum  $filingFrequency
     * @param  ?LocalDate  $createFilingsFrom
     * @param  ?bool  $isApproaching
     * @param  ?string  $comment
     * @param  ?bool  $vda
     * @param  ?string  $taxId
     * @param  ?string  $iorNumber
     * @phpstan-pure
     */
    public function __construct(?LocalDate $registrationDate = null, ?string $registrationEmail = null, ?\DateTime $registrationRequested = null, ?\DateTime $registrationCompleted = null, ?\DateTime $deregistrationRequested = null, ?\DateTime $deregistrationCompleted = null, ?bool $autoRegistered = null, ?RegistrationsRegimeEnum $registrationsRegime = null, ?ChangeRegimeStatusEnum $changeRegimeStatus = null, ?bool $thirdPartyEnabled = null, ?bool $twoFactorEnabled = null, ?bool $markedCollecting = null, ?string $encryptedUsername = null, ?string $username = null, ?FilingFrequencyEnum $filingFrequency = null, ?LocalDate $createFilingsFrom = null, ?bool $isApproaching = null, ?string $comment = null, ?bool $vda = null, ?string $taxId = null, ?string $iorNumber = null, ?bool $doNotFile = false, ?bool $createBackFiling = false)
    {
        $this->registrationDate = $registrationDate;
        $this->registrationEmail = $registrationEmail;
        $this->registrationRequested = $registrationRequested;
        $this->registrationCompleted = $registrationCompleted;
        $this->deregistrationRequested = $deregistrationRequested;
        $this->deregistrationCompleted = $deregistrationCompleted;
        $this->autoRegistered = $autoRegistered;
        $this->registrationsRegime = $registrationsRegime;
        $this->changeRegimeStatus = $changeRegimeStatus;
        $this->thirdPartyEnabled = $thirdPartyEnabled;
        $this->twoFactorEnabled = $twoFactorEnabled;
        $this->markedCollecting = $markedCollecting;
        $this->encryptedUsername = $encryptedUsername;
        $this->username = $username;
        $this->filingFrequency = $filingFrequency;
        $this->createFilingsFrom = $createFilingsFrom;
        $this->isApproaching = $isApproaching;
        $this->comment = $comment;
        $this->vda = $vda;
        $this->taxId = $taxId;
        $this->iorNumber = $iorNumber;
        $this->doNotFile = $doNotFile;
        $this->createBackFiling = $createBackFiling;
    }
}