<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;

use OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class Security
{
    /**
     *
     * @var ?string $apiKeyHeader
     */
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=X-API-KEY')]
    public ?string $apiKeyHeader = null;

    /**
     * @param  ?string  $apiKeyHeader
     * @phpstan-pure
     */
    public function __construct(?string $apiKeyHeader = null)
    {
        $this->apiKeyHeader = $apiKeyHeader;
    }
}