<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** Current state of the credit note in its lifecycle. */
enum Status: string
{
    case Pending = 'PENDING';
    case Cancelled = 'CANCELLED';
    case Committed = 'COMMITTED';
}
