<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


enum TaxItemTypeEnum: string
{
    case Imported = 'IMPORTED';
    case Calculated = 'CALCULATED';
}
