<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


class TaxItemBuilder
{
    /**
     *
     * @var float $rate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rate')]
    public float $rate;

    /**
     *
     * @var float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public float $amount;

    /**
     * Deprecated: use `jurisdiction_type` instead
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public string $organizationId;

    /**
     *
     * @var ?float $convertedAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('converted_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $convertedAmount = null;

    /**
     *
     * @var ?CurrencyEnum $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CurrencyEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CurrencyEnum $currency = null;

    /**
     *
     * @var ?CurrencyEnum $destinationCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CurrencyEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CurrencyEnum $destinationCurrency = null;

    /**
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     *
     * @var ?TaxItemTypeEnum $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\TaxItemTypeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TaxItemTypeEnum $type = null;

    /**
     *
     * @var ?JurisdictionType $jurisdictionType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('jurisdiction_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\JurisdictionType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?JurisdictionType $jurisdictionType = null;

    /**
     *
     * @var ?string $jurisdictionName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('jurisdiction_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $jurisdictionName = null;

    /**
     * The rule ID of the tax item
     *
     * @var ?string $ruleId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rule_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ruleId = null;

    /**
     * @param  float  $rate
     * @param  float  $amount
     * @param  string  $name
     * @param  string  $organizationId
     * @param  ?string  $ruleId
     * @param  ?float  $convertedAmount
     * @param  ?CurrencyEnum  $currency
     * @param  ?CurrencyEnum  $destinationCurrency
     * @param  ?string  $externalId
     * @param  ?TaxItemTypeEnum  $type
     * @param  ?JurisdictionType  $jurisdictionType
     * @param  ?string  $jurisdictionName
     * @phpstan-pure
     */
    public function __construct(float $rate, float $amount, string $name, string $organizationId, ?float $convertedAmount = null, ?CurrencyEnum $currency = null, ?CurrencyEnum $destinationCurrency = null, ?string $externalId = null, ?TaxItemTypeEnum $type = null, ?JurisdictionType $jurisdictionType = null, ?string $jurisdictionName = null, ?string $ruleId = '0000')
    {
        $this->rate = $rate;
        $this->amount = $amount;
        $this->name = $name;
        $this->organizationId = $organizationId;
        $this->convertedAmount = $convertedAmount;
        $this->currency = $currency;
        $this->destinationCurrency = $destinationCurrency;
        $this->externalId = $externalId;
        $this->type = $type;
        $this->jurisdictionType = $jurisdictionType;
        $this->jurisdictionName = $jurisdictionName;
        $this->ruleId = $ruleId;
    }
}