<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


enum TaxItemTypeEnum: string
{
    case ImportedOriginal = 'IMPORTED_ORIGINAL';
    case Imported = 'IMPORTED';
    case Calculated = 'CALCULATED';
}
