<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


enum TennesseeRegistrationType: string
{
    case ConsumersUseTax = 'CONSUMERS_USE_TAX';
    case SalesTax = 'SALES_TAX';
    case UseTax = 'USE_TAX';
}
