<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


class TransactionImportCustomer
{
    /**
     *
     * @var ?SourceEnum $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\SourceEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SourceEnum $source = null;

    /**
     *
     * @var ?AddressStatus $addressStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\AddressStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AddressStatus $addressStatus = null;

    /**
     * Phone number associated with the address.
     *
     * @var ?string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phone = null;

    /**
     * Primary street address.
     *
     * @var ?string $street1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('street_1')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $street1 = null;

    /**
     * Additional street address details, such as an apartment or suite number.
     *
     * @var ?string $street2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('street_2')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $street2 = null;

    /**
     * City where the customer resides.
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $city = null;

    /**
     * County or district of the customer.
     *
     * @var ?string $county
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('county')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $county = null;

    /**
     * State or province of the customer.
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     * ZIP or Postal code of the customer.
     *
     * @var ?string $postalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postal_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $postalCode = null;

    /**
     * Country code in ISO 3166-1 alpha-2 format
     *
     * @var ?CountryCodeEnum $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\CountryCodeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CountryCodeEnum $country = null;

    /**
     * Complete address string of the customer, which can be used as an alternative to individual fields.
     *
     * @var ?string $fullAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('full_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $fullAddress = null;

    /**
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $organizationId = null;

    /**
     *
     * @var ?string $connectionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connection_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $connectionId = null;

    /**
     *
     * @var ?string $registrationNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $registrationNumber = null;

    /**
     * @param  ?SourceEnum  $source
     * @param  ?AddressStatus  $addressStatus
     * @param  ?string  $phone
     * @param  ?string  $street1
     * @param  ?string  $street2
     * @param  ?string  $city
     * @param  ?string  $county
     * @param  ?string  $state
     * @param  ?string  $postalCode
     * @param  ?CountryCodeEnum  $country
     * @param  ?string  $fullAddress
     * @param  ?string  $externalId
     * @param  ?string  $name
     * @param  ?string  $email
     * @param  ?string  $organizationId
     * @param  ?string  $connectionId
     * @param  ?string  $registrationNumber
     * @phpstan-pure
     */
    public function __construct(?SourceEnum $source = null, ?AddressStatus $addressStatus = null, ?string $phone = null, ?string $street1 = null, ?string $street2 = null, ?string $city = null, ?string $county = null, ?string $state = null, ?string $postalCode = null, ?CountryCodeEnum $country = null, ?string $fullAddress = null, ?string $externalId = null, ?string $name = null, ?string $email = null, ?string $organizationId = null, ?string $connectionId = null, ?string $registrationNumber = null)
    {
        $this->source = $source;
        $this->addressStatus = $addressStatus;
        $this->phone = $phone;
        $this->street1 = $street1;
        $this->street2 = $street2;
        $this->city = $city;
        $this->county = $county;
        $this->state = $state;
        $this->postalCode = $postalCode;
        $this->country = $country;
        $this->fullAddress = $fullAddress;
        $this->externalId = $externalId;
        $this->name = $name;
        $this->email = $email;
        $this->organizationId = $organizationId;
        $this->connectionId = $connectionId;
        $this->registrationNumber = $registrationNumber;
    }
}