<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


class TransactionPublicRequest
{
    /**
     * Unique identifier of the organization. This field is deprecated, and should no longer be used. The value is populated through the 'x-organization-id' header.
     *
     * @var string $organizationId
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public string $organizationId;

    /**
     * External identifier of the transaction.
     *
     * @var string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    public string $externalId;

    /**
     * Transaction date and time
     *
     * @var \DateTime $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public \DateTime $date;

    /**
     * $addresses
     *
     * @var array<TransactionAddressPublic> $addresses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addresses')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\KintsugiTax\SDK\Models\Components\TransactionAddressPublic>')]
    public array $addresses;

    /**
     * $transactionItems
     *
     * @var array<TransactionItemBuilder> $transactionItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transaction_items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\KintsugiTax\SDK\Models\Components\TransactionItemBuilder>')]
    public array $transactionItems;

    /**
     *
     * @var CustomerBaseBase $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CustomerBaseBase')]
    public CustomerBaseBase $customer;

    /**
     *
     * @var TransactionTypeEnum $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\TransactionTypeEnum')]
    public TransactionTypeEnum $type;

    /**
     *
     * @var ?ExemptionRequired $requiresExemption
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('requires_exemption')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\ExemptionRequired|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ExemptionRequired $requiresExemption = null;

    /**
     * Transaction date in the shop's local timezone
     *
     * @var ?string $shopDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('shop_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $shopDate = null;

    /**
     * Timezone of the shop
     *
     * @var ?string $shopDateTz
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('shop_date_tz')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $shopDateTz = null;

    /**
     * Description of the transaction.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Shopify has 2 order statuses for refund case: refunded and partially_refunded
     *
     * If the given order has different status from these 2, we will set the
     * transaction's refund_status to PARTIALLY_REFUNDED by default.
     *
     * @var ?TransactionRefundStatus $refundStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refund_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\TransactionRefundStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TransactionRefundStatus $refundStatus = null;

    /**
     * Unique identifier of the customer.
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     * Based on transaction item exempt status.
     *
     * NOT EXEMPT: None of the items are NOT EXEMPT
     * PARTIALLY EXEMPT: At least some of the items are NOT EXEMPT
     * FULLY_EXEMPT: All items sold in the transaction are EXEMPT
     * ZERO_RATE_NOT_EXEMPT: All items sold in the transaction are zero-rated
     *
     * @var ?TransactionExemptStatusEnum $exempt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exempt')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\TransactionExemptStatusEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TransactionExemptStatusEnum $exempt = null;

    /**
     * List of exemptions applied (if any).
     *
     * @var ?array<Exemption> $exemptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exemptions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\KintsugiTax\SDK\Models\Components\Exemption>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $exemptions = null;

    /**
     * Related transaction identifier.
     *
     * @var ?string $relatedTo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('related_to')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $relatedTo = null;

    /**
     * Secondary External Identifier.
     *
     * @var ?string $secondaryExternalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('secondary_external_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $secondaryExternalId = null;

    /**
     * Secondary source information
     *
     * @var ?string $secondarySource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('secondary_source')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $secondarySource = null;

    /**
     * Friendly identifier of the original item.
     *
     * @var ?string $externalFriendlyId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_friendly_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalFriendlyId = null;

    /**
     *
     * @var ?TaxLiabilitySourceEnum $taxLiabilitySource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_liability_source')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\TaxLiabilitySourceEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TaxLiabilitySourceEnum $taxLiabilitySource = null;

    /**
     *
     * @var ?CurrencyEnum $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CurrencyEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CurrencyEnum $currency = null;

    /**
     *
     * @var ?SourceEnum $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\SourceEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SourceEnum $source = null;

    /**
     * Connection Identifier
     *
     * @var ?string $connectionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connection_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $connectionId = null;

    /**
     * Filing identifier.
     *
     * @var ?string $filingId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('filing_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $filingId = null;

    /**
     * City of the transaction address.
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $city = null;

    /**
     * County of the transaction address.
     *
     * @var ?string $county
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('county')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $county = null;

    /**
     * State of the transaction address.
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     *
     * @var ?CountryCodeEnum $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\CountryCodeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CountryCodeEnum $country = null;

    /**
     * Postal code of the transaction.
     *
     * @var ?string $postalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postal_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $postalCode = null;

    /**
     * Tax ID associated with the transaction. DEPRECATED: This field is only populated for QuickBooks integrations and will be removed in a future version.
     *
     * @var ?string $taxId
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxId = null;

    /**
     *
     * @var ?TransactionStatusEnum $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\TransactionStatusEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TransactionStatusEnum $status = null;

    /**
     * Total amount of the transaction.
     *
     * @var ?float $totalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $totalAmount = null;

    /**
     * Indicates if transaction is marketplace-based.
     *
     * @var ?bool $marketplace
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('marketplace')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $marketplace = null;

    /**
     * Imported tax amount.
     *
     * @var ?float $totalTaxAmountImported
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_tax_amount_imported')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $totalTaxAmountImported = null;

    /**
     * Imported tax rate.
     *
     * @var ?float $taxRateImported
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_rate_imported')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $taxRateImported = null;

    /**
     * Calculated tax amount.
     *
     * @var ?float $totalTaxAmountCalculated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_tax_amount_calculated')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $totalTaxAmountCalculated = null;

    /**
     * Calculated tax rate.
     *
     * @var ?float $taxRateCalculated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_rate_calculated')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $taxRateCalculated = null;

    /**
     * Total tax liability amount.
     *
     * @var ?float $totalTaxLiabilityAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_tax_liability_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $totalTaxLiabilityAmount = null;

    /**
     * Taxable amount.
     *
     * @var ?float $taxableAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('taxable_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $taxableAmount = null;

    /**
     * Transaction lock status.
     *
     * @var ?bool $locked
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('locked')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $locked = null;

    /**
     * @param  string  $organizationId
     * @param  string  $externalId
     * @param  \DateTime  $date
     * @param  array<TransactionAddressPublic>  $addresses
     * @param  array<TransactionItemBuilder>  $transactionItems
     * @param  CustomerBaseBase  $customer
     * @param  TransactionTypeEnum  $type
     * @param  ?ExemptionRequired  $requiresExemption
     * @param  ?string  $shopDate
     * @param  ?string  $shopDateTz
     * @param  ?string  $description
     * @param  ?TransactionRefundStatus  $refundStatus
     * @param  ?float  $totalAmount
     * @param  ?string  $customerId
     * @param  ?bool  $marketplace
     * @param  ?TransactionExemptStatusEnum  $exempt
     * @param  ?array<Exemption>  $exemptions
     * @param  ?string  $relatedTo
     * @param  ?string  $secondaryExternalId
     * @param  ?string  $secondarySource
     * @param  ?string  $externalFriendlyId
     * @param  ?float  $totalTaxAmountImported
     * @param  ?float  $taxRateImported
     * @param  ?float  $totalTaxAmountCalculated
     * @param  ?float  $taxRateCalculated
     * @param  ?float  $totalTaxLiabilityAmount
     * @param  ?TaxLiabilitySourceEnum  $taxLiabilitySource
     * @param  ?float  $taxableAmount
     * @param  ?CurrencyEnum  $currency
     * @param  ?bool  $locked
     * @param  ?SourceEnum  $source
     * @param  ?string  $connectionId
     * @param  ?string  $filingId
     * @param  ?string  $city
     * @param  ?string  $county
     * @param  ?string  $state
     * @param  ?CountryCodeEnum  $country
     * @param  ?string  $postalCode
     * @param  ?string  $taxId
     * @param  ?TransactionStatusEnum  $status
     * @phpstan-pure
     */
    public function __construct(string $organizationId, string $externalId, \DateTime $date, array $addresses, array $transactionItems, CustomerBaseBase $customer, TransactionTypeEnum $type, ?ExemptionRequired $requiresExemption = null, ?string $shopDate = null, ?string $shopDateTz = null, ?string $description = null, ?TransactionRefundStatus $refundStatus = null, ?string $customerId = null, ?TransactionExemptStatusEnum $exempt = null, ?array $exemptions = null, ?string $relatedTo = null, ?string $secondaryExternalId = null, ?string $secondarySource = null, ?string $externalFriendlyId = null, ?TaxLiabilitySourceEnum $taxLiabilitySource = null, ?CurrencyEnum $currency = null, ?SourceEnum $source = null, ?string $connectionId = null, ?string $filingId = null, ?string $city = null, ?string $county = null, ?string $state = null, ?CountryCodeEnum $country = null, ?string $postalCode = null, ?string $taxId = null, ?TransactionStatusEnum $status = null, ?float $totalAmount = 0.00, ?bool $marketplace = false, ?float $totalTaxAmountImported = 0.00, ?float $taxRateImported = 0.00, ?float $totalTaxAmountCalculated = 0.00, ?float $taxRateCalculated = 0.00, ?float $totalTaxLiabilityAmount = 0.00, ?float $taxableAmount = 0.00, ?bool $locked = false)
    {
        $this->organizationId = $organizationId;
        $this->externalId = $externalId;
        $this->date = $date;
        $this->addresses = $addresses;
        $this->transactionItems = $transactionItems;
        $this->customer = $customer;
        $this->type = $type;
        $this->requiresExemption = $requiresExemption;
        $this->shopDate = $shopDate;
        $this->shopDateTz = $shopDateTz;
        $this->description = $description;
        $this->refundStatus = $refundStatus;
        $this->customerId = $customerId;
        $this->exempt = $exempt;
        $this->exemptions = $exemptions;
        $this->relatedTo = $relatedTo;
        $this->secondaryExternalId = $secondaryExternalId;
        $this->secondarySource = $secondarySource;
        $this->externalFriendlyId = $externalFriendlyId;
        $this->taxLiabilitySource = $taxLiabilitySource;
        $this->currency = $currency;
        $this->source = $source;
        $this->connectionId = $connectionId;
        $this->filingId = $filingId;
        $this->city = $city;
        $this->county = $county;
        $this->state = $state;
        $this->country = $country;
        $this->postalCode = $postalCode;
        $this->taxId = $taxId;
        $this->status = $status;
        $this->totalAmount = $totalAmount;
        $this->marketplace = $marketplace;
        $this->totalTaxAmountImported = $totalTaxAmountImported;
        $this->taxRateImported = $taxRateImported;
        $this->totalTaxAmountCalculated = $totalTaxAmountCalculated;
        $this->taxRateCalculated = $taxRateCalculated;
        $this->totalTaxLiabilityAmount = $totalTaxLiabilityAmount;
        $this->taxableAmount = $taxableAmount;
        $this->locked = $locked;
    }
}