<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


class TransactionItemEstimateBase
{
    /**
     * The date of the transaction item.
     *
     * @var \DateTime $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public \DateTime $date;

    /**
     * The total amount of the item.
     *
     * @var float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public float $amount;

    /**
     * A unique identifier for the transaction item.
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     * A description of the item.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * External product identifier. If not found and product_subcategory
     *
     *         and product_category are not provided, an error occurs.
     *
     * @var ?string $externalProductId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_product_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalProductId = null;

    /**
     * Name of the product. Used if creating a new product.
     *
     * @var ?string $productName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $productName = null;

    /**
     * Description of the product. Used if creating a new product.
     *
     * @var ?string $productDescription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $productDescription = null;

    /**
     *
     * @var ?SourceEnum $productSource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_source')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\SourceEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SourceEnum $productSource = null;

    /**
     * Subcategory of the product. Required if product_category is used
     *
     *         in place of external_product_id.
     *
     * @var ?string $productSubcategory
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_subcategory')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $productSubcategory = null;

    /**
     * Category of the product. Required if product_subcategory is used
     *
     *         in place of external_product_id.
     *
     * @var ?string $productCategory
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_category')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $productCategory = null;

    /**
     * Defaults to 1.0. The quantity of the item.
     *
     * @var ?float $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $quantity = null;

    /**
     * Defaults to false. Indicates whether the item is exempt from tax.
     *
     * @var ?bool $exempt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exempt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $exempt = null;

    /**
     * @param  \DateTime  $date
     * @param  float  $amount
     * @param  ?string  $externalId
     * @param  ?string  $description
     * @param  ?string  $externalProductId
     * @param  ?string  $productName
     * @param  ?string  $productDescription
     * @param  ?SourceEnum  $productSource
     * @param  ?string  $productSubcategory
     * @param  ?string  $productCategory
     * @param  ?float  $quantity
     * @param  ?bool  $exempt
     * @phpstan-pure
     */
    public function __construct(\DateTime $date, float $amount, ?string $externalId = null, ?string $description = null, ?string $externalProductId = null, ?string $productName = null, ?string $productDescription = null, ?SourceEnum $productSource = null, ?string $productSubcategory = null, ?string $productCategory = null, ?float $quantity = 1.0, ?bool $exempt = false)
    {
        $this->date = $date;
        $this->amount = $amount;
        $this->externalId = $externalId;
        $this->description = $description;
        $this->externalProductId = $externalProductId;
        $this->productName = $productName;
        $this->productDescription = $productDescription;
        $this->productSource = $productSource;
        $this->productSubcategory = $productSubcategory;
        $this->productCategory = $productCategory;
        $this->quantity = $quantity;
        $this->exempt = $exempt;
    }
}