<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;

use Brick\DateTime\LocalDate;
class TransactionCreate
{
    /**
     * Unique identifier of the organization.
     *
     * @var string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public string $organizationId;

    /**
     * External identifier of the transaction.
     *
     * @var string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    public string $externalId;

    /**
     * Transaction date and time
     *
     * @var \DateTime $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public \DateTime $date;

    /**
     *
     * @var array<TransactionAddressBuilder>|array<AddressInput> $addresses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addresses')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\OpenAPI\OpenAPI\Models\Components\TransactionAddressBuilder>|array<\OpenAPI\OpenAPI\Models\Components\AddressInput>')]
    public array $addresses;

    /**
     * $transactionItems
     *
     * @var array<TransactionItemCreateUpdate> $transactionItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transaction_items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\OpenAPI\OpenAPI\Models\Components\TransactionItemCreateUpdate>')]
    public array $transactionItems;

    /**
     *
     * @var ?TransactionStatusEnum $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\TransactionStatusEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TransactionStatusEnum $status = null;

    /**
     * Total amount of the transaction.
     *
     * @var float|string|null $totalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_amount')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $totalAmount = null;

    /**
     * Imported tax amount.
     *
     * @var float|string|null $totalTaxAmountImported
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_tax_amount_imported')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $totalTaxAmountImported = null;

    /**
     * Imported tax rate.
     *
     * @var float|string|null $taxRateImported
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_rate_imported')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $taxRateImported = null;

    /**
     * Calculated tax amount.
     *
     * @var float|string|null $totalTaxAmountCalculated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_tax_amount_calculated')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $totalTaxAmountCalculated = null;

    /**
     * Calculated tax rate.
     *
     * @var float|string|null $taxRateCalculated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_rate_calculated')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $taxRateCalculated = null;

    /**
     * Total tax liability amount.
     *
     * @var float|string|null $totalTaxLiabilityAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_tax_liability_amount')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $totalTaxLiabilityAmount = null;

    /**
     * Taxable amount.
     *
     * @var float|string|null $taxableAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('taxable_amount')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $taxableAmount = null;

    /**
     *
     * @var ?CurrencyEnum $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\CurrencyEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CurrencyEnum $currency = null;

    /**
     *
     * @var ?SourceEnum $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\SourceEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SourceEnum $source = null;

    /**
     *
     * @var ?AddressStatus $addressStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\AddressStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AddressStatus $addressStatus = null;

    /**
     * Our transaction state, used to determine when/if a transaction needs additional
     *
     * processing.
     *
     * @var ?ProcessingStatusEnum $processingStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('processing_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\ProcessingStatusEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ProcessingStatusEnum $processingStatus = null;

    /**
     * Indicates if transaction requires tax exemption.
     *
     * @var ?ExemptionRequired $requiresExemption
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('requires_exemption')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\ExemptionRequired|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ExemptionRequired $requiresExemption = null;

    /**
     * Transaction date in the shop's local timezone
     *
     * @var ?LocalDate $shopDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('shop_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $shopDate = null;

    /**
     * Timezone of the shop
     *
     * @var ?string $shopDateTz
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('shop_date_tz')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $shopDateTz = null;

    /**
     * Description of the transaction.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Status of refund, if applicable
     *
     * @var ?TransactionRefundStatus $refundStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refund_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\TransactionRefundStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TransactionRefundStatus $refundStatus = null;

    /**
     * Unique identifier of the customer.
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     * Indicates if transaction is marketplace-based.
     *
     * @var ?bool $marketplace
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('marketplace')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $marketplace = null;

    /**
     * Exemption status (e.g., NOT_EXEMPT)
     *
     * @var ?TransactionExemptStatusEnum $exempt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exempt')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\TransactionExemptStatusEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TransactionExemptStatusEnum $exempt = null;

    /**
     * List of exemptions applied (if any).
     *
     * @var ?array<Exemption> $exemptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exemptions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\OpenAPI\OpenAPI\Models\Components\Exemption>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $exemptions = null;

    /**
     * Related transaction identifier.
     *
     * @var ?string $relatedTo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('related_to')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $relatedTo = null;

    /**
     * Secondary External Identifier.
     *
     * @var ?string $secondaryExternalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('secondary_external_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $secondaryExternalId = null;

    /**
     * Secondary source information
     *
     * @var ?string $secondarySource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('secondary_source')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $secondarySource = null;

    /**
     * Friendly identifier of the original item.
     *
     * @var ?string $externalFriendlyId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_friendly_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalFriendlyId = null;

    /**
     * Source of tax liability.
     *
     * @var ?TaxLiabilitySourceEnum $taxLiabilitySource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_liability_source')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\TaxLiabilitySourceEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TaxLiabilitySourceEnum $taxLiabilitySource = null;

    /**
     * Connection Identifier
     *
     * @var ?string $connectionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connection_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $connectionId = null;

    /**
     * Filing identifier.
     *
     * @var ?string $filingId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('filing_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $filingId = null;

    /**
     * City of the transaction address.
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $city = null;

    /**
     * County of the transaction address.
     *
     * @var ?string $county
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('county')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $county = null;

    /**
     * State of the transaction address.
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     * Country code (ISO Alpha-2).
     *
     * @var ?CountryCodeEnum $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\CountryCodeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CountryCodeEnum $country = null;

    /**
     * Postal code of the transaction.
     *
     * @var ?string $postalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postal_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $postalCode = null;

    /**
     * Tax ID associated with the transaction
     *
     * @var ?string $taxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxId = null;

    /**
     * Destination currency code (ISO 4217, e.g., USD)
     *
     * @var ?CurrencyEnum $destinationCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\CurrencyEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CurrencyEnum $destinationCurrency = null;

    /**
     * Converted total amount.
     *
     * @var float|string|null $convertedTotalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('converted_total_amount')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $convertedTotalAmount = null;

    /**
     * Converted imported tax amount.
     *
     * @var float|string|null $convertedTotalTaxAmountImported
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('converted_total_tax_amount_imported')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $convertedTotalTaxAmountImported = null;

    /**
     * Converted calculated tax amount.
     *
     * @var float|string|null $convertedTotalTaxAmountCalculated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('converted_total_tax_amount_calculated')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $convertedTotalTaxAmountCalculated = null;

    /**
     * Currency conversion rate.
     *
     * @var float|string|null $conversionRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conversion_rate')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $conversionRate = null;

    /**
     * Converted taxable amount.
     *
     * @var float|string|null $convertedTaxableAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('converted_taxable_amount')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $convertedTaxableAmount = null;

    /**
     * Converted total discount amount.
     *
     * @var float|string|null $convertedTotalDiscount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('converted_total_discount')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $convertedTotalDiscount = null;

    /**
     * Converted subtotal amount.
     *
     * @var float|string|null $convertedSubtotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('converted_subtotal')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $convertedSubtotal = null;

    /**
     * Converted total tax liability amount.
     *
     * @var float|string|null $convertedTotalTaxLiabilityAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('converted_total_tax_liability_amount')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $convertedTotalTaxLiabilityAmount = null;

    /**
     *
     * @var ?CustomerCreate $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\CustomerCreate|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CustomerCreate $customer = null;

    /**
     * Transaction lock status.
     *
     * @var ?bool $locked
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('locked')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $locked = null;

    /**
     * @param  string  $organizationId
     * @param  string  $externalId
     * @param  \DateTime  $date
     * @param  array<TransactionAddressBuilder>|array<AddressInput>  $addresses
     * @param  array<TransactionItemCreateUpdate>  $transactionItems
     * @param  ?TransactionStatusEnum  $status
     * @param  float|string|null  $totalAmount
     * @param  float|string|null  $totalTaxAmountImported
     * @param  float|string|null  $taxRateImported
     * @param  float|string|null  $totalTaxAmountCalculated
     * @param  float|string|null  $taxRateCalculated
     * @param  float|string|null  $totalTaxLiabilityAmount
     * @param  float|string|null  $taxableAmount
     * @param  ?CurrencyEnum  $currency
     * @param  ?bool  $locked
     * @param  ?SourceEnum  $source
     * @param  ?AddressStatus  $addressStatus
     * @param  ?ProcessingStatusEnum  $processingStatus
     * @param  ?ExemptionRequired  $requiresExemption
     * @param  ?LocalDate  $shopDate
     * @param  ?string  $shopDateTz
     * @param  ?string  $description
     * @param  ?TransactionRefundStatus  $refundStatus
     * @param  ?string  $customerId
     * @param  ?bool  $marketplace
     * @param  ?TransactionExemptStatusEnum  $exempt
     * @param  ?array<Exemption>  $exemptions
     * @param  ?string  $relatedTo
     * @param  ?string  $secondaryExternalId
     * @param  ?string  $secondarySource
     * @param  ?string  $externalFriendlyId
     * @param  ?TaxLiabilitySourceEnum  $taxLiabilitySource
     * @param  ?string  $connectionId
     * @param  ?string  $filingId
     * @param  ?string  $city
     * @param  ?string  $county
     * @param  ?string  $state
     * @param  ?CountryCodeEnum  $country
     * @param  ?string  $postalCode
     * @param  ?string  $taxId
     * @param  ?CurrencyEnum  $destinationCurrency
     * @param  float|string|null  $convertedTotalAmount
     * @param  float|string|null  $convertedTotalTaxAmountImported
     * @param  float|string|null  $convertedTotalTaxAmountCalculated
     * @param  float|string|null  $conversionRate
     * @param  float|string|null  $convertedTaxableAmount
     * @param  float|string|null  $convertedTotalDiscount
     * @param  float|string|null  $convertedSubtotal
     * @param  float|string|null  $convertedTotalTaxLiabilityAmount
     * @param  ?CustomerCreate  $customer
     * @phpstan-pure
     */
    public function __construct(string $organizationId, string $externalId, \DateTime $date, array $addresses, array $transactionItems, ?TransactionStatusEnum $status = null, float|string|null $totalAmount = null, float|string|null $totalTaxAmountImported = null, float|string|null $taxRateImported = null, float|string|null $totalTaxAmountCalculated = null, float|string|null $taxRateCalculated = null, float|string|null $totalTaxLiabilityAmount = null, float|string|null $taxableAmount = null, ?CurrencyEnum $currency = null, ?SourceEnum $source = null, ?AddressStatus $addressStatus = null, ?ProcessingStatusEnum $processingStatus = null, ?ExemptionRequired $requiresExemption = null, ?LocalDate $shopDate = null, ?string $shopDateTz = null, ?string $description = null, ?TransactionRefundStatus $refundStatus = null, ?string $customerId = null, ?bool $marketplace = null, ?TransactionExemptStatusEnum $exempt = null, ?array $exemptions = null, ?string $relatedTo = null, ?string $secondaryExternalId = null, ?string $secondarySource = null, ?string $externalFriendlyId = null, ?TaxLiabilitySourceEnum $taxLiabilitySource = null, ?string $connectionId = null, ?string $filingId = null, ?string $city = null, ?string $county = null, ?string $state = null, ?CountryCodeEnum $country = null, ?string $postalCode = null, ?string $taxId = null, ?CurrencyEnum $destinationCurrency = null, float|string|null $convertedTotalAmount = null, float|string|null $convertedTotalTaxAmountImported = null, float|string|null $convertedTotalTaxAmountCalculated = null, float|string|null $conversionRate = null, float|string|null $convertedTaxableAmount = null, float|string|null $convertedTotalDiscount = null, float|string|null $convertedSubtotal = null, float|string|null $convertedTotalTaxLiabilityAmount = null, ?CustomerCreate $customer = null, ?bool $locked = false)
    {
        $this->organizationId = $organizationId;
        $this->externalId = $externalId;
        $this->date = $date;
        $this->addresses = $addresses;
        $this->transactionItems = $transactionItems;
        $this->status = $status;
        $this->totalAmount = $totalAmount;
        $this->totalTaxAmountImported = $totalTaxAmountImported;
        $this->taxRateImported = $taxRateImported;
        $this->totalTaxAmountCalculated = $totalTaxAmountCalculated;
        $this->taxRateCalculated = $taxRateCalculated;
        $this->totalTaxLiabilityAmount = $totalTaxLiabilityAmount;
        $this->taxableAmount = $taxableAmount;
        $this->currency = $currency;
        $this->source = $source;
        $this->addressStatus = $addressStatus;
        $this->processingStatus = $processingStatus;
        $this->requiresExemption = $requiresExemption;
        $this->shopDate = $shopDate;
        $this->shopDateTz = $shopDateTz;
        $this->description = $description;
        $this->refundStatus = $refundStatus;
        $this->customerId = $customerId;
        $this->marketplace = $marketplace;
        $this->exempt = $exempt;
        $this->exemptions = $exemptions;
        $this->relatedTo = $relatedTo;
        $this->secondaryExternalId = $secondaryExternalId;
        $this->secondarySource = $secondarySource;
        $this->externalFriendlyId = $externalFriendlyId;
        $this->taxLiabilitySource = $taxLiabilitySource;
        $this->connectionId = $connectionId;
        $this->filingId = $filingId;
        $this->city = $city;
        $this->county = $county;
        $this->state = $state;
        $this->country = $country;
        $this->postalCode = $postalCode;
        $this->taxId = $taxId;
        $this->destinationCurrency = $destinationCurrency;
        $this->convertedTotalAmount = $convertedTotalAmount;
        $this->convertedTotalTaxAmountImported = $convertedTotalTaxAmountImported;
        $this->convertedTotalTaxAmountCalculated = $convertedTotalTaxAmountCalculated;
        $this->conversionRate = $conversionRate;
        $this->convertedTaxableAmount = $convertedTaxableAmount;
        $this->convertedTotalDiscount = $convertedTotalDiscount;
        $this->convertedSubtotal = $convertedSubtotal;
        $this->convertedTotalTaxLiabilityAmount = $convertedTotalTaxLiabilityAmount;
        $this->customer = $customer;
        $this->locked = $locked;
    }
}