<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


/**
 * TransactionEstimateRequest - Request model for tax estimation, including all fields from TransactionEstimateBase
 *
 * and an additional field to simulate nexus being met.
 */
class TransactionEstimateRequest
{
    /**
     * The date of the transaction in ISO 8601 format (e.g., 2025-01-25T12:00:00Z).
     *
     * @var \DateTime $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public \DateTime $date;

    /**
     * Unique identifier of this transaction in the source system.
     *
     * @var string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    public string $externalId;

    /**
     *
     * @var CurrencyEnum $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\CurrencyEnum')]
    public CurrencyEnum $currency;

    /**
     * List of addresses related to the transaction. At least one BILL_TO or SHIP_TO address must be provided. The address will be validated during estimation, and the transaction may be rejected if the address does not pass validation. The SHIP_TO will be preferred to use for determining tax liability. **Deprecated:** Use of `address.status` in estimate api is ignored and will be removed in the future status will be considered UNVERIFIED by default and always validated
     *
     * @var array<TransactionEstimateRequestAddress> $addresses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addresses')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\OpenAPI\OpenAPI\Models\Components\TransactionEstimateRequestAddress>')]
    public array $addresses;

    /**
     * List of items involved in the transaction.
     *
     * @var array<TransactionItemEstimateBase> $transactionItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transaction_items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\OpenAPI\OpenAPI\Models\Components\TransactionItemEstimateBase>')]
    public array $transactionItems;

    /**
     * Total amount of the transaction.
     *
     * @var float|string|null $totalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_amount')]
    #[\Speakeasy\Serializer\Annotation\Type('float|string|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public float|string|null $totalAmount = null;

    /**
     * An optional description of the transaction.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * While currently not used, it may be used in the future to determine taxability. The source of the transaction (e.g., OTHER).
     *
     * @var ?SourceEnum $source
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\SourceEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SourceEnum $source = null;

    /**
     * Indicates if the transaction involves a marketplace.
     *
     * @var ?bool $marketplace
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('marketplace')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $marketplace = null;

    /**
     * Details about the customer. If the customer is not found, it will be ignored.
     *
     * @var ?CustomerBaseInput $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Models\Components\CustomerBaseInput|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CustomerBaseInput $customer = null;

    /**
     * If True, assumes active registration is met for tax estimation.
     *
     * @var ?bool $simulateActiveRegistration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('simulate_active_registration')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $simulateActiveRegistration = null;

    /**
     * Use simulate_active_registration instead.
     *
     *         This field will be removed in future releases.
     *
     * @var ?bool $simulateNexusMet
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('simulate_nexus_met')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $simulateNexusMet = null;

    /**
     * @param  \DateTime  $date
     * @param  string  $externalId
     * @param  CurrencyEnum  $currency
     * @param  array<TransactionEstimateRequestAddress>  $addresses
     * @param  array<TransactionItemEstimateBase>  $transactionItems
     * @param  float|string|null  $totalAmount
     * @param  ?string  $description
     * @param  ?SourceEnum  $source
     * @param  ?bool  $marketplace
     * @param  ?CustomerBaseInput  $customer
     * @param  ?bool  $simulateActiveRegistration
     * @param  ?bool  $simulateNexusMet
     * @phpstan-pure
     */
    public function __construct(\DateTime $date, string $externalId, CurrencyEnum $currency, array $addresses, array $transactionItems, float|string|null $totalAmount = null, ?string $description = null, ?SourceEnum $source = null, ?bool $marketplace = null, ?CustomerBaseInput $customer = null, ?bool $simulateActiveRegistration = null, ?bool $simulateNexusMet = null)
    {
        $this->date = $date;
        $this->externalId = $externalId;
        $this->currency = $currency;
        $this->addresses = $addresses;
        $this->transactionItems = $transactionItems;
        $this->totalAmount = $totalAmount;
        $this->description = $description;
        $this->source = $source;
        $this->marketplace = $marketplace;
        $this->customer = $customer;
        $this->simulateActiveRegistration = $simulateActiveRegistration;
        $this->simulateNexusMet = $simulateNexusMet;
    }
}