<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


enum TransactionTypeEnum: string
{
    case Sale = 'SALE';
    case FullCreditNote = 'FULL_CREDIT_NOTE';
    case PartialCreditNote = 'PARTIAL_CREDIT_NOTE';
    case TaxRefund = 'TAX_REFUND';
    case Archive = 'ARCHIVE';
}
