<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


enum TreatmentEnum: string
{
    case Included = 'INCLUDED';
    case Excluded = 'EXCLUDED';
    case Depends = 'DEPENDS';
    case YesSalesNoTransactions = 'YES_SALES_NO_TRANSACTIONS';
}
