<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** UtahFields - State-specific fields for Utah TAP portal registration import. */
class UtahFields
{
    /**
     *
     * @var \KintsugiTax\SDK\Models\Components\UtahRegistrationType $registrationType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\UtahRegistrationType')]
    public UtahRegistrationType $registrationType;

    /**
     * State-registered business name as shown in Utah TAP.
     *
     * @var string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_name')]
    public string $businessName;

    /**
     * Utah state-issued tax identification number (UT State Tax ID).
     *
     * @var string $utStateTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ut_state_tax_id')]
    public string $utStateTaxId;

    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Utah tax account.
     *
     * @var ?bool $mfaCompleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mfa_completed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $mfaCompleted = null;

    /**
     * @param  \KintsugiTax\SDK\Models\Components\UtahRegistrationType  $registrationType
     * @param  string  $businessName
     * @param  string  $utStateTaxId
     * @param  ?bool  $mfaCompleted
     * @phpstan-pure
     */
    public function __construct(UtahRegistrationType $registrationType, string $businessName, string $utStateTaxId, ?bool $mfaCompleted = false)
    {
        $this->registrationType = $registrationType;
        $this->businessName = $businessName;
        $this->utStateTaxId = $utStateTaxId;
        $this->mfaCompleted = $mfaCompleted;
    }
}