<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** WestVirginiaFields - State-specific fields for West Virginia MyTaxes portal registration import. */
class WestVirginiaFields
{
    /**
     *
     * @var \KintsugiTax\SDK\Models\Components\WestVirginiaRegistrationType $registrationType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\WestVirginiaRegistrationType')]
    public WestVirginiaRegistrationType $registrationType;

    /**
     * State-registered business name as shown in West Virginia MyTaxes.
     *
     * @var string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_name')]
    public string $businessName;

    /**
     * West Virginia state-issued tax identification number (WV State Tax ID).
     *
     * @var string $wvStateTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('wv_state_tax_id')]
    public string $wvStateTaxId;

    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their West Virginia MyTaxes account.
     *
     * @var ?bool $mfaCompleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mfa_completed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $mfaCompleted = null;

    /**
     * Whether third-party access has been granted to Kintsugi in MyTaxes.
     *
     * @var ?bool $thirdPartyAccessEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('third_party_access_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $thirdPartyAccessEnabled = null;

    /**
     * @param  \KintsugiTax\SDK\Models\Components\WestVirginiaRegistrationType  $registrationType
     * @param  string  $businessName
     * @param  string  $wvStateTaxId
     * @param  ?bool  $mfaCompleted
     * @param  ?bool  $thirdPartyAccessEnabled
     * @phpstan-pure
     */
    public function __construct(WestVirginiaRegistrationType $registrationType, string $businessName, string $wvStateTaxId, ?bool $mfaCompleted = false, ?bool $thirdPartyAccessEnabled = false)
    {
        $this->registrationType = $registrationType;
        $this->businessName = $businessName;
        $this->wvStateTaxId = $wvStateTaxId;
        $this->mfaCompleted = $mfaCompleted;
        $this->thirdPartyAccessEnabled = $thirdPartyAccessEnabled;
    }
}