<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/** WisconsinFields - State-specific fields for Wisconsin MyTaxAccount portal registration import. */
class WisconsinFields
{
    /**
     *
     * @var \KintsugiTax\SDK\Models\Components\WisconsinRegistrationType $registrationType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\KintsugiTax\SDK\Models\Components\WisconsinRegistrationType')]
    public WisconsinRegistrationType $registrationType;

    /**
     * State-registered business name as shown in Wisconsin MyTaxAccount.
     *
     * @var string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_name')]
    public string $businessName;

    /**
     * Wisconsin state-issued tax identification number (WI State Tax ID).
     *
     * @var string $wiStateTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('wi_state_tax_id')]
    public string $wiStateTaxId;

    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Wisconsin MyTaxAccount.
     *
     * @var ?bool $mfaCompleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mfa_completed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $mfaCompleted = null;

    /**
     * Whether third-party access has been granted to Kintsugi in MyTaxAccount.
     *
     * @var ?bool $thirdPartyAccessEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('third_party_access_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $thirdPartyAccessEnabled = null;

    /**
     * @param  \KintsugiTax\SDK\Models\Components\WisconsinRegistrationType  $registrationType
     * @param  string  $businessName
     * @param  string  $wiStateTaxId
     * @param  ?bool  $mfaCompleted
     * @param  ?bool  $thirdPartyAccessEnabled
     * @phpstan-pure
     */
    public function __construct(WisconsinRegistrationType $registrationType, string $businessName, string $wiStateTaxId, ?bool $mfaCompleted = false, ?bool $thirdPartyAccessEnabled = false)
    {
        $this->registrationType = $registrationType;
        $this->businessName = $businessName;
        $this->wiStateTaxId = $wiStateTaxId;
        $this->mfaCompleted = $mfaCompleted;
        $this->thirdPartyAccessEnabled = $thirdPartyAccessEnabled;
    }
}