<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace KintsugiTax\SDK\Models\Components;


/**
 * WyomingFields - State-specific fields for Wyoming (WYPath) registration import.
 *
 *
 * Wyoming (WYIFS / WYPath) does not use or require 2FA/MFA, so there is no
 * ``mfa_completed`` field. There is also no dedicated third-party master account
 * for sales and use tax, so there is no ``third_party_access_enabled`` field.
 * The State PIN is collected via the optional top-level ``pin_plain_text`` field
 * (encrypted into ``pin_encrypted``), not JSF — same pattern as Arizona.
 */
class WyomingFields
{
    /**
     * State-registered business name as shown in Wyoming WYPath.
     *
     * @var string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_name')]
    public string $businessName;

    /**
     * Wyoming state-issued tax ID (Wyoming State Tax ID).
     *
     * @var string $wyStateTaxId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('wy_state_tax_id')]
    public string $wyStateTaxId;

    /**
     * Registration type for this Wyoming import: sales and use tax.
     *
     * @var string $registrationType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registration_type')]
    public string $registrationType;

    /**
     * @param  string  $registrationType
     * @param  string  $businessName
     * @param  string  $wyStateTaxId
     * @phpstan-pure
     */
    public function __construct(string $businessName, string $wyStateTaxId, string $registrationType = 'SALES_AND_USE_TAX')
    {
        $this->businessName = $businessName;
        $this->wyStateTaxId = $wyStateTaxId;
        $this->registrationType = $registrationType;
    }
}